CREATE TABLE [RedShift_swisscard].[booking_event] (
    [booking_eventId]                                      BIGINT         IDENTITY (1, 1) NOT NULL,
    [id]                                                   NVARCHAR (512) NULL,
    [received_at]                                          DATETIME2 (7)  NULL,
    [uuid]                                                 BIGINT         NULL,
    [context_page_path]                                    NVARCHAR (512) NULL,
    [event]                                                NVARCHAR (512) NULL,
    [original_timestamp]                                   NVARCHAR (50)  NULL,
    [type]                                                 NVARCHAR (512) NULL,
    [uuid_ts]                                              NVARCHAR (50)  NULL,
    [event_text]                                           NVARCHAR (512) NULL,
    [anonymous_id]                                         NVARCHAR (512) NULL,
    [booking_data_data_confirmed_terms]                    VARCHAR (5)    NULL,
    [booking_data_data_preferred_contact_method]           NVARCHAR (512) NULL,
    [context_ip]                                           NVARCHAR (512) NULL,
    [context_library_name]                                 NVARCHAR (512) NULL,
    [context_page_url]                                     NVARCHAR (512) NULL,
    [context_library_version]                              NVARCHAR (512) NULL,
    [context_page_title]                                   NVARCHAR (512) NULL,
    [context_user_agent]                                   NVARCHAR (512) NULL,
    [sent_at]                                              NVARCHAR (50)  NULL,
    [timestamp]                                            NVARCHAR (50)  NULL,
    [user_id]                                              NVARCHAR (512) NULL,
    [booking_data_data_use_saved_card]                     VARCHAR (5)    NULL,
    [booking_data_data_hotel_sub_bookings]                 NVARCHAR (512) NULL,
    [booking_data_data_payment_card_valid]                 VARCHAR (5)    NULL,
    [booking_data_data_billing_address]                    NVARCHAR (512) NULL,
    [booking_data_data_car_hire_sub_bookings]              NVARCHAR (512) NULL,
    [booking_data_data_flight_sub_bookings]                NVARCHAR (512) NULL,
    [context_page_referrer]                                NVARCHAR (512) NULL,
    [booking_data_data_delivery_method]                    NVARCHAR (512) NULL,
    [context_page_search]                                  NVARCHAR (512) NULL,
    [booking_data_id]                                      NVARCHAR (512) NULL,
    [booking_data_data_browser_info_java_enabled]          VARCHAR (5)    NULL,
    [booking_data_data_browser_info_timezone_offset]       BIGINT         NULL,
    [booking_data_data_browser_info_screen_width]          BIGINT         NULL,
    [booking_data_data_browser_info_screen_height]         BIGINT         NULL,
    [booking_data_data_browser_info_color_depth]           BIGINT         NULL,
    [booking_data_data_browser_info_language]              NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_city]          NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_type]          NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_house_number]  NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_postcode]      NVARCHAR (512) NULL,
    [securely_store_card_checkbox]                         NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_house_name]    NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_id]            BIGINT         NULL,
    [booking_data_data_billing_address_data_preferred]     VARCHAR (5)    NULL,
    [booking_data_data_billing_address_data_url]           NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_address_line1] NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_country]       NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_longitude]     NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_latitude]      NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_state]         NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_address_line2] NVARCHAR (512) NULL,
    [booking_data_data_0_document_number]                  NVARCHAR (512) NULL,
    [booking_data_data_0_document_nationality_name]        NVARCHAR (512) NULL,
    [booking_data_data_0_document_nationality]             NVARCHAR (512) NULL,
    [booking_data_data_0_document_issue_date]              NVARCHAR (50)  NULL,
    [booking_data_data_0_traveller]                        NVARCHAR (512) NULL,
    [booking_data_data_0_document_type]                    NVARCHAR (512) NULL,
    [booking_data_data_0_document_expiry_date]             NVARCHAR (50)  NULL,
    [booking_data_data_0_document_issuing_country_name]    NVARCHAR (512) NULL,
    [booking_data_data_0_document_issuing_country]         NVARCHAR (512) NULL,
    [event_id]                                             BIGINT         NULL,
    [event_name]                                           NVARCHAR (512) NULL,
    CONSTRAINT [PK_RedShift_swisscard_booking_eventId] PRIMARY KEY CLUSTERED ([booking_eventId] ASC)
);

