CREATE TABLE [RedShift_swisscard].[dining_search_button] (
    [dining_search_buttonID]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [id]                      NVARCHAR (512) NULL,
    [received_at]             DATETIME2 (7)  NULL,
    [uuid]                    BIGINT         NULL,
    [context_ip]              NVARCHAR (512) NULL,
    [context_locale]          NVARCHAR (512) NULL,
    [context_page_title]      NVARCHAR (512) NULL,
    [date_time_local]         DATETIME2 (7)  NULL,
    [event]                   NVARCHAR (512) NULL,
    [guests]                  BIGINT         NULL,
    [timestamp]               DATETIME2 (7)  NULL,
    [context_library_version] NVARCHAR (512) NULL,
    [context_page_path]       NVARCHAR (512) NULL,
    [context_page_search]     NVARCHAR (512) NULL,
    [original_timestamp]      DATETIME2 (7)  NULL,
    [search_phrase]           NVARCHAR (512) NULL,
    [anonymous_id]            NVARCHAR (512) NULL,
    [context_library_name]    NVARCHAR (512) NULL,
    [user_id]                 NVARCHAR (512) NULL,
    [uuid_ts]                 DATETIME2 (7)  NULL,
    [context_page_referrer]   NVARCHAR (512) NULL,
    [context_page_url]        NVARCHAR (512) NULL,
    [context_user_agent]      NVARCHAR (512) NULL,
    [event_text]              NVARCHAR (512) NULL,
    [sent_at]                 DATETIME2 (7)  NULL,
    CONSTRAINT [PK_dining_search_buttonID] PRIMARY KEY CLUSTERED ([dining_search_buttonID] ASC)
);

