CREATE TABLE [RedShift_swisscard].[search] (
    [id]                                            NVARCHAR (512) NULL,
    [received_at]                                   DATETIME2 (6)  NULL,
    [uuid]                                          BIGINT         NULL,
    [properties_query_object_type]                  NVARCHAR (512) NULL,
    [properties_query_start_date_full]              DATETIME2 (6)  NULL,
    [properties_query_start_location]               NVARCHAR (512) NULL,
    [context_page_path]                             NVARCHAR (512) NULL,
    [user_id]                                       NVARCHAR (512) NULL,
    [anonymous_id]                                  NVARCHAR (512) NULL,
    [context_user_agent]                            NVARCHAR (512) NULL,
    [event]                                         NVARCHAR (512) NULL,
    [event_text]                                    NVARCHAR (512) NULL,
    [context_ip]                                    NVARCHAR (512) NULL,
    [context_locale]                                NVARCHAR (512) NULL,
    [properties_query_end_date_full]                DATETIME2 (6)  NULL,
    [properties_sub_module]                         NVARCHAR (512) NULL,
    [context_page_url]                              NVARCHAR (512) NULL,
    [properties_query_selected_start_location_name] NVARCHAR (512) NULL,
    [original_timestamp]                            DATETIME2 (6)  NULL,
    [context_library_name]                          NVARCHAR (512) NULL,
    [context_page_title]                            NVARCHAR (512) NULL,
    [uuid_ts]                                       DATETIME2 (6)  NULL,
    [properties_module]                             NVARCHAR (512) NULL,
    [context_library_version]                       NVARCHAR (512) NULL,
    [context_page_referrer]                         NVARCHAR (512) NULL,
    [timestamp]                                     DATETIME2 (6)  NULL,
    [properties_query_room_requests]                NVARCHAR (512) NULL,
    [sent_at]                                       DATETIME2 (6)  NULL,
    [properties_query]                              NVARCHAR (512) NULL,
    [context_page_search]                           NVARCHAR (512) NULL,
    [properties_query_end_location]                 NVARCHAR (512) NULL,
    [properties_query_flight_class]                 NVARCHAR (512) NULL,
    [properties_query_selected_end_location_name]   NVARCHAR (512) NULL,
    [properties_query_driver_age]                   BIGINT         NULL,
    [properties_query_end_object_type]              NVARCHAR (512) NULL,
    [properties_query_start_time]                   NVARCHAR (512) NULL,
    [properties_query_num_adults]                   BIGINT         NULL,
    [properties_query_num_infants]                  BIGINT         NULL,
    [properties_query_children_ages]                NVARCHAR (512) NULL,
    [properties_query_end_time]                     NVARCHAR (512) NULL,
    [properties_query_airline]                      BIGINT         NULL,
    [module]                                        NVARCHAR (512) NULL,
    [query]                                         NVARCHAR (512) NULL,
    [query_flight_class]                            NVARCHAR (512) NULL,
    [query_selected_start_location_name]            NVARCHAR (512) NULL,
    [sub_module]                                    NVARCHAR (512) NULL,
    [query_num_infants]                             BIGINT         NULL,
    [query_end_time]                                NVARCHAR (512) NULL,
    [query_end_date_full]                           DATETIME2 (6)  NULL,
    [query_object_type]                             NVARCHAR (512) NULL,
    [query_room_requests]                           NVARCHAR (512) NULL,
    [query_end_object_type]                         NVARCHAR (512) NULL,
    [query_start_location]                          NVARCHAR (512) NULL,
    [query_num_adults]                              BIGINT         NULL,
    [query_driver_age]                              BIGINT         NULL,
    [query_children_ages]                           NVARCHAR (512) NULL,
    [query_selected_end_location_name]              NVARCHAR (512) NULL,
    [query_start_time]                              NVARCHAR (512) NULL,
    [query_end_location]                            NVARCHAR (512) NULL,
    [query_start_date_full]                         DATETIME2 (6)  NULL,
    [query_airline]                                 BIGINT         NULL,
    [query_num_young_adults]                        BIGINT         NULL,
    [filters]                                       NVARCHAR (512) NULL,
    [query_selected_flight_type]                    NVARCHAR (512) NULL,
    [query_same_depot]                              BIT            NULL
);

