CREATE TABLE [IBMWatson].[TenGroupUKandSA] (
    [TenGroupUKandSAId]    INT              IDENTITY (1, 1) NOT NULL,
    [Member_ID]            NVARCHAR (1000)  NULL,
    [Email]                NVARCHAR (1000)  NULL,
    [RECIPIENT_ID]         NVARCHAR (1000)  NULL,
    [Status]               NVARCHAR (1000)  NULL,
    [GDPR_Optin]           NVARCHAR (1000)  NULL,
    [Allows_Marketing]     NVARCHAR (1000)  NULL,
    [Reg]                  NVARCHAR (1000)  NULL,
    [Opt In Date]          NVARCHAR (1000)  NULL,
    [Open date]            NVARCHAR (1000)  NULL,
    [Scheme_ID]            NVARCHAR (1000)  NULL,
    [Ten Group Employee]   NVARCHAR (1000)  NULL,
    [Lifestyle_Lowdown]    NVARCHAR (1000)  NULL,
    [Dining]               NVARCHAR (1000)  NULL,
    [Music]                NVARCHAR (1000)  NULL,
    [Retail]               NVARCHAR (1000)  NULL,
    [Events]               NVARCHAR (1000)  NULL,
    [Travel]               NVARCHAR (1000)  NULL,
    [Theatre]              NVARCHAR (1000)  NULL,
    [Art]                  NVARCHAR (1000)  NULL,
    [Attractions]          NVARCHAR (1000)  NULL,
    [Sports]               NVARCHAR (1000)  NULL,
    [Send_platform_invite] NVARCHAR (1000)  NULL,
    [Inserted_On]          DATETIME         NULL,
    [FileName]             NVARCHAR (1000)  NULL,
    [ProcessId]            UNIQUEIDENTIFIER NULL,
    CONSTRAINT [UQ_IBMWatson_TenGroupUKandSA_TenGroupUKandSAId_20200116] UNIQUE NONCLUSTERED ([TenGroupUKandSAId] ASC)
);

