CREATE TABLE [IBMWatson].[zzCompletedTransactionalNPS_bkup_tengroup7866_20240226] (
    [CompletedTransactionalNPSId]                                                                                            INT              IDENTITY (1, 1) NOT NULL,
    [Email]                                                                                                                  NVARCHAR (1000)  NULL,
    [Opt In Date]                                                                                                            NVARCHAR (1000)  NULL,
    [Opted Out]                                                                                                              NVARCHAR (1000)  NULL,
    [Opt In Details]                                                                                                         NVARCHAR (1000)  NULL,
    [Email Type]                                                                                                             NVARCHAR (1000)  NULL,
    [Opted Out Date]                                                                                                         NVARCHAR (1000)  NULL,
    [Opt Out Details]                                                                                                        NVARCHAR (1000)  NULL,
    [1JimTestField11]                                                                                                        NVARCHAR (1000)  NULL,
    [Activation_URL]                                                                                                         NVARCHAR (1000)  NULL,
    [All_Marketing]                                                                                                          NVARCHAR (1000)  NULL,
    [Allows_Marketing]                                                                                                       NVARCHAR (1000)  NULL,
    [Any_other_comments_on_the_service]                                                                                      NVARCHAR (1000)  NULL,
    [Art]                                                                                                                    NVARCHAR (1000)  NULL,
    [Attractions]                                                                                                            NVARCHAR (1000)  NULL,
    [Attractions_count]                                                                                                      NVARCHAR (1000)  NULL,
    [BD_Contact]                                                                                                             NVARCHAR (1000)  NULL,
    [BD_Email]                                                                                                               NVARCHAR (1000)  NULL,
    [Birthday]                                                                                                               NVARCHAR (1000)  NULL,
    [Brief]                                                                                                                  NVARCHAR (1000)  NULL,
    [Brief_date]                                                                                                             NVARCHAR (1000)  NULL,
    [Charlie_test]                                                                                                           NVARCHAR (1000)  NULL,
    [Cinema_Code]                                                                                                            NVARCHAR (1000)  NULL,
    [City]                                                                                                                   NVARCHAR (1000)  NULL,
    [Clicked date]                                                                                                           NVARCHAR (1000)  NULL,
    [Client Employee]                                                                                                        NVARCHAR (1000)  NULL,
    [ClosedDate]                                                                                                             NVARCHAR (1000)  NULL,
    [Closed_by]                                                                                                              NVARCHAR (1000)  NULL,
    [Closed_by_sub_team]                                                                                                     NVARCHAR (1000)  NULL,
    [Closed_by_team]                                                                                                         NVARCHAR (1000)  NULL,
    [Code]                                                                                                                   NVARCHAR (1000)  NULL,
    [Code1]                                                                                                                  NVARCHAR (1000)  NULL,
    [Code10]                                                                                                                 NVARCHAR (1000)  NULL,
    [Code2]                                                                                                                  NVARCHAR (1000)  NULL,
    [Code3]                                                                                                                  NVARCHAR (1000)  NULL,
    [Code4]                                                                                                                  NVARCHAR (1000)  NULL,
    [Code5]                                                                                                                  NVARCHAR (1000)  NULL,
    [Code6]                                                                                                                  NVARCHAR (1000)  NULL,
    [Code7]                                                                                                                  NVARCHAR (1000)  NULL,
    [Code8]                                                                                                                  NVARCHAR (1000)  NULL,
    [Consent]                                                                                                                NVARCHAR (1000)  NULL,
    [Country]                                                                                                                NVARCHAR (1000)  NULL,
    [Date]                                                                                                                   NVARCHAR (1000)  NULL,
    [DateOfBirth]                                                                                                            NVARCHAR (1000)  NULL,
    [Date_Joined]                                                                                                            NVARCHAR (1000)  NULL,
    [Date_Member_Created]                                                                                                    NVARCHAR (1000)  NULL,
    [DepDate]                                                                                                                NVARCHAR (1000)  NULL,
    [Departure_Date]                                                                                                         NVARCHAR (1000)  NULL,
    [Dept]                                                                                                                   NVARCHAR (1000)  NULL,
    [Did_LM_Give_Deadline]                                                                                                   NVARCHAR (1000)  NULL,
    [Did_You_Receive_Response_On_Time]                                                                                       NVARCHAR (1000)  NULL,
    [Did_you_get_what_you_were_looking_for]                                                                                  NVARCHAR (1000)  NULL,
    [Dining]                                                                                                                 NVARCHAR (1000)  NULL,
    [Dining_count]                                                                                                           NVARCHAR (1000)  NULL,
    [Do_you_feel_there_was_added_value_to_your_research_or_booking_when_you_used_the_concierge]                              NVARCHAR (1000)  NULL,
    [Does_the_value_of_the_concierge_service_make_you_more_likely_to_recommend_X_banking_service_to_a_friend_or_a_colleague] NVARCHAR (1000)  NULL,
    [Dolphin_ID]                                                                                                             NVARCHAR (1000)  NULL,
    [Dont call back RE NPS]                                                                                                  NVARCHAR (1000)  NULL,
    [Editorial test list]                                                                                                    NVARCHAR (1000)  NULL,
    [Employee_ID]                                                                                                            NVARCHAR (1000)  NULL,
    [Event]                                                                                                                  NVARCHAR (1000)  NULL,
    [Event_attended]                                                                                                         NVARCHAR (1000)  NULL,
    [Event_date]                                                                                                             NVARCHAR (1000)  NULL,
    [Event_score]                                                                                                            NVARCHAR (1000)  NULL,
    [Events]                                                                                                                 NVARCHAR (1000)  NULL,
    [Extension]                                                                                                              NVARCHAR (1000)  NULL,
    [Family_activities]                                                                                                      NVARCHAR (1000)  NULL,
    [Farfetch_Code]                                                                                                          NVARCHAR (1000)  NULL,
    [Feedback_Count]                                                                                                         NVARCHAR (1000)  NULL,
    [First_Name]                                                                                                             NVARCHAR (1000)  NULL,
    [First_Name_Encoded]                                                                                                     NVARCHAR (1000)  NULL,
    [Flights]                                                                                                                NVARCHAR (1000)  NULL,
    [Flights_count]                                                                                                          NVARCHAR (1000)  NULL,
    [Formula_1]                                                                                                              NVARCHAR (1000)  NULL,
    [GDPR_Optin]                                                                                                             NVARCHAR (1000)  NULL,
    [Gender]                                                                                                                 NVARCHAR (1000)  NULL,
    [Golf]                                                                                                                   NVARCHAR (1000)  NULL,
    [Golf_count]                                                                                                             NVARCHAR (1000)  NULL,
    [Group]                                                                                                                  NVARCHAR (1000)  NULL,
    [Group1]                                                                                                                 NVARCHAR (1000)  NULL,
    [GroupType]                                                                                                              NVARCHAR (1000)  NULL,
    [Have_you_used_the_new_online_concierge service]                                                                         NVARCHAR (1000)  NULL,
    [Hoe_beoordeelt_u_het_professionalisme_van_onze_Travel_en_Lifestyle_specialisten]                                        NVARCHAR (1000)  NULL,
    [Home]                                                                                                                   NVARCHAR (1000)  NULL,
    [Home_count]                                                                                                             NVARCHAR (1000)  NULL,
    [Hotels]                                                                                                                 NVARCHAR (1000)  NULL,
    [Hotels_count]                                                                                                           NVARCHAR (1000)  NULL,
    [How_could_improve_online_concierge_for_you]                                                                             NVARCHAR (1000)  NULL,
    [How_much_did_you_enjoy_the_event]                                                                                       NVARCHAR (1000)  NULL,
    [How_satisfied_were_you_with_the_speed_of_response]                                                                      NVARCHAR (1000)  NULL,
    [How_would_you_rate_the_Lifestyle_Managers_professionalism_and_expertise]                                                NVARCHAR (1000)  NULL,
    [How_would_you_rate_your_LAM]                                                                                            NVARCHAR (1000)  NULL,
    [If_no_would_you_like_to_be_sent_an_invitation_to_register_for_the_online_concierge_service]                             NVARCHAR (1000)  NULL,
    [If_you_have_used_the_new_online_service_to_what_extent_did_it_enhance_your_experience_of_concierge]                     NVARCHAR (1000)  NULL,
    [Indicate_here_if_you_do_not_want_to_receive_a_call_back_from_us_to_further_understand_your_feedback]                    NVARCHAR (1000)  NULL,
    [Invite_url]                                                                                                             NVARCHAR (1000)  NULL,
    [JobID]                                                                                                                  INT              NULL,
    [LM Office]                                                                                                              NVARCHAR (1000)  NULL,
    [LM_ID]                                                                                                                  NVARCHAR (1000)  NULL,
    [Language]                                                                                                               NVARCHAR (1000)  NULL,
    [Last name]                                                                                                              NVARCHAR (1000)  NULL,
    [Last_Brief_Date]                                                                                                        NVARCHAR (1000)  NULL,
    [Lifestyle Manager]                                                                                                      NVARCHAR (1000)  NULL,
    [Lifestyle_Lowdown]                                                                                                      NVARCHAR (1000)  NULL,
    [Member Group Name]                                                                                                      NVARCHAR (1000)  NULL,
    [Member_ID]                                                                                                              NVARCHAR (1000)  NULL,
    [Member_events]                                                                                                          NVARCHAR (1000)  NULL,
    [Member_offers]                                                                                                          NVARCHAR (1000)  NULL,
    [Merge_field]                                                                                                            NVARCHAR (1000)  NULL,
    [Mobile_number]                                                                                                          NVARCHAR (1000)  NULL,
    [Motor]                                                                                                                  NVARCHAR (1000)  NULL,
    [Motor_count]                                                                                                            NVARCHAR (1000)  NULL,
    [Music]                                                                                                                  NVARCHAR (1000)  NULL,
    [Music_count]                                                                                                            NVARCHAR (1000)  NULL,
    [NPS scoring_Behavior]                                                                                                   NVARCHAR (1000)  NULL,
    [NPS scoring_Rank]                                                                                                       NVARCHAR (1000)  NULL,
    [NPS scoring_Score]                                                                                                      NVARCHAR (1000)  NULL,
    [NPS test field]                                                                                                         NVARCHAR (1000)  NULL,
    [NPS1]                                                                                                                   NVARCHAR (1000)  NULL,
    [NPSMonth]                                                                                                               NVARCHAR (1000)  NULL,
    [NPS_Alpha_Professionalism_Expertise]                                                                                    NVARCHAR (1000)  NULL,
    [NPS_Alpha_Speed_Of_Reply]                                                                                               NVARCHAR (1000)  NULL,
    [NPS_Any_other_comments]                                                                                                 NVARCHAR (4000)  NULL,
    [NPS_Best_feature_of_the_card]                                                                                           NVARCHAR (1000)  NULL,
    [NPS_China_Q1]                                                                                                           NVARCHAR (1000)  NULL,
    [NPS_China_Q2]                                                                                                           NVARCHAR (1000)  NULL,
    [NPS_China_Q3]                                                                                                           NVARCHAR (1000)  NULL,
    [NPS_China_Q4]                                                                                                           NVARCHAR (1000)  NULL,
    [NPS_Communication_Interaction]                                                                                          NVARCHAR (1000)  NULL,
    [NPS_Concierge_Influence_To_Renew_Diners_Card]                                                                           NVARCHAR (1000)  NULL,
    [NPS_Content_Of_Our_Reply]                                                                                               NVARCHAR (1000)  NULL,
    [NPS_Ease_Of_Contact]                                                                                                    NVARCHAR (1000)  NULL,
    [NPS_JPN_Reason_For_Scores]                                                                                              NVARCHAR (1000)  NULL,
    [NPS_Language_And_Manner]                                                                                                NVARCHAR (1000)  NULL,
    [NPS_Mindfulness_Of_LM]                                                                                                  NVARCHAR (1000)  NULL,
    [NPS_Overall_Request_Handling]                                                                                           NVARCHAR (1000)  NULL,
    [NPS_Overall_Response_Time]                                                                                              NVARCHAR (1000)  NULL,
    [NPS_Professionalism_Expertise]                                                                                          NVARCHAR (1000)  NULL,
    [NPS_Quality_Of_Offers]                                                                                                  NVARCHAR (1000)  NULL,
    [NPS_Recent_Type]                                                                                                        NVARCHAR (1000)  NULL,
    [NPS_Request_type]                                                                                                       NVARCHAR (1000)  NULL,
    [NPS_Response_In_Deadline]                                                                                               NVARCHAR (1000)  NULL,
    [NPS_Scheme_ID]                                                                                                          NVARCHAR (1000)  NULL,
    [NPS_Specialism_of_LM]                                                                                                   NVARCHAR (1000)  NULL,
    [NPS_Speed_Of_Reply]                                                                                                     NVARCHAR (1000)  NULL,
    [NPS_Swiss_Any_other_comments]                                                                                           NVARCHAR (1000)  NULL,
    [NPS_To_What_Extent_Does_Concierge_Influence_You_To_Continue_With_Diners_Premium_card]                                   NVARCHAR (1000)  NULL,
    [NPS_Value_For_Money]                                                                                                    NVARCHAR (1000)  NULL,
    [NPS_What_Do_You_Expect_Most_From_Concierge]                                                                             NVARCHAR (1000)  NULL,
    [NPS_Which_aspects_do_you_perceive_as_added_value]                                                                       NVARCHAR (1000)  NULL,
    [NPS_Which_aspects_do_you_perceive_as_added_value_OTHER]                                                                 NVARCHAR (1000)  NULL,
    [NPS_score]                                                                                                              NVARCHAR (1000)  NULL,
    [Night_clubs]                                                                                                            NVARCHAR (1000)  NULL,
    [Office]                                                                                                                 NVARCHAR (1000)  NULL,
    [Open date]                                                                                                              NVARCHAR (1000)  NULL,
    [Opera]                                                                                                                  NVARCHAR (1000)  NULL,
    [Opera_count]                                                                                                            NVARCHAR (1000)  NULL,
    [Option colour]                                                                                                          NVARCHAR (1000)  NULL,
    [Overall_how_easy_was_it_to_get_the_help_you_wanted]                                                                     NVARCHAR (1000)  NULL,
    [Please_provide_any_feedback_on_the_event]                                                                               NVARCHAR (1000)  NULL,
    [Postcode]                                                                                                               NVARCHAR (1000)  NULL,
    [Postcode_End]                                                                                                           NVARCHAR (1000)  NULL,
    [Postcode_Start]                                                                                                         NVARCHAR (1000)  NULL,
    [Primary_member_ID]                                                                                                      NVARCHAR (1000)  NULL,
    [Privateguestlist]                                                                                                       NVARCHAR (1000)  NULL,
    [Reference1]                                                                                                             NVARCHAR (1000)  NULL,
    [Reference2]                                                                                                             NVARCHAR (1000)  NULL,
    [Reference3]                                                                                                             NVARCHAR (1000)  NULL,
    [Reg]                                                                                                                    NVARCHAR (1000)  NULL,
    [RegDate]                                                                                                                NVARCHAR (1000)  NULL,
    [Retail]                                                                                                                 NVARCHAR (1000)  NULL,
    [Retail_count]                                                                                                           NVARCHAR (1000)  NULL,
    [Scheme_ID]                                                                                                              NVARCHAR (1000)  NULL,
    [Send_hour]                                                                                                              NVARCHAR (1000)  NULL,
    [Send_info]                                                                                                              NVARCHAR (1000)  NULL,
    [Send_platform_invite]                                                                                                   NVARCHAR (1000)  NULL,
    [Sent Date]                                                                                                              NVARCHAR (1000)  NULL,
    [Sent_on_survey]                                                                                                         NVARCHAR (1000)  NULL,
    [Sports]                                                                                                                 NVARCHAR (1000)  NULL,
    [Sports_count]                                                                                                           NVARCHAR (1000)  NULL,
    [Status]                                                                                                                 NVARCHAR (1000)  NULL,
    [Subject]                                                                                                                NVARCHAR (1000)  NULL,
    [Surname]                                                                                                                NVARCHAR (1000)  NULL,
    [SurveyReplyFrom]                                                                                                        NVARCHAR (1000)  NULL,
    [SurveyReplyTo]                                                                                                          NVARCHAR (1000)  NULL,
    [SurveyUrl]                                                                                                              NVARCHAR (1000)  NULL,
    [Ten Group Employee]                                                                                                     NVARCHAR (1000)  NULL,
    [Tenmaid_Dept]                                                                                                           NVARCHAR (1000)  NULL,
    [Test]                                                                                                                   NVARCHAR (1000)  NULL,
    [The_service_provided_me_with_better_options_value_or_access_than_I_could_have_found_on_my_own]                          NVARCHAR (1000)  NULL,
    [Theatre]                                                                                                                NVARCHAR (1000)  NULL,
    [Theatre_count]                                                                                                          NVARCHAR (1000)  NULL,
    [Title]                                                                                                                  NVARCHAR (1000)  NULL,
    [Todays date]                                                                                                            NVARCHAR (1000)  NULL,
    [Travel]                                                                                                                 NVARCHAR (1000)  NULL,
    [Travel_count]                                                                                                           NVARCHAR (1000)  NULL,
    [VEP_email]                                                                                                              NVARCHAR (1000)  NULL,
    [VEP_favorite_singer]                                                                                                    NVARCHAR (1000)  NULL,
    [VEP_favorite_writer]                                                                                                    NVARCHAR (1000)  NULL,
    [VEP_movies]                                                                                                             NVARCHAR (1000)  NULL,
    [VEP_music]                                                                                                              NVARCHAR (1000)  NULL,
    [VEP_music_streaming]                                                                                                    NVARCHAR (1000)  NULL,
    [VEP_other_ents]                                                                                                         NVARCHAR (1000)  NULL,
    [VEP_print]                                                                                                              NVARCHAR (1000)  NULL,
    [VEP_theater]                                                                                                            NVARCHAR (1000)  NULL,
    [VEP_video_streaming]                                                                                                    NVARCHAR (1000)  NULL,
    [VEP_videogames]                                                                                                         NVARCHAR (1000)  NULL,
    [VIP_Hospitality]                                                                                                        NVARCHAR (1000)  NULL,
    [V_C]                                                                                                                    NVARCHAR (1000)  NULL,
    [Web behaviour_Behavior]                                                                                                 NVARCHAR (1000)  NULL,
    [Web behaviour_Rank]                                                                                                     NVARCHAR (1000)  NULL,
    [Web behaviour_Score]                                                                                                    NVARCHAR (1000)  NULL,
    [Were_you_pleased_with_the_speed_of_response_on_your_request]                                                            NVARCHAR (3000)  NULL,
    [What_do_you_feel_is_the_most_important_service_improvement_we_could_make]                                               NVARCHAR (3000)  NULL,
    [What_events_would_you_like_to_be_invited_to_in_the_future]                                                              NVARCHAR (3000)  NULL,
    [Which_aspects_do_you_perceive_as_added_value]                                                                           NVARCHAR (3000)  NULL,
    [Which_aspects_of_the_service_positively_affected_your_NPS_score]                                                        NVARCHAR (3000)  NULL,
    [Would_you_agree_that_all_aspects_of_your_request_were_attended_to]                                                      NVARCHAR (3000)  NULL,
    [Would_you_be_happy_to_receive_a_call_back_so_that_we_can_better_understand_your_feedback]                               NVARCHAR (1000)  NULL,
    [avaloqid_ref1]                                                                                                          NVARCHAR (1000)  NULL,
    [classiccard]                                                                                                            NVARCHAR (1000)  NULL,
    [complaint_count]                                                                                                        NVARCHAR (1000)  NULL,
    [count_job]                                                                                                              NVARCHAR (1000)  NULL,
    [division_ref3]                                                                                                          NVARCHAR (1000)  NULL,
    [merge_field2]                                                                                                           NVARCHAR (1000)  NULL,
    [npscode]                                                                                                                NVARCHAR (1000)  NULL,
    [nwbtransferjobs]                                                                                                        NVARCHAR (1000)  NULL,
    [oldbpltranfermid]                                                                                                       NVARCHAR (1000)  NULL,
    [oldmidnwbc]                                                                                                             NVARCHAR (1000)  NULL,
    [parentdomain]                                                                                                           NVARCHAR (1000)  NULL,
    [pb_ref2]                                                                                                                NVARCHAR (1000)  NULL,
    [radiuscode]                                                                                                             NVARCHAR (1000)  NULL,
    [remove_these]                                                                                                           NVARCHAR (1000)  NULL,
    [scheme]                                                                                                                 NVARCHAR (1000)  NULL,
    [warmingcode]                                                                                                            NVARCHAR (1000)  NULL,
    [Inserted_On]                                                                                                            DATETIME         NULL,
    [FileName]                                                                                                               NVARCHAR (1000)  NULL,
    [ProcessId]                                                                                                              UNIQUEIDENTIFIER NULL,
    [PM_LM_takes_ownership_of_requests]                                                                                      NVARCHAR (1000)  NULL,
    [PM_additional_feedback]                                                                                                 NVARCHAR (1000)  NULL,
    [PM_are_requests_dealt_with_promptly]                                                                                    NVARCHAR (1000)  NULL,
    [PM_do_you_trust_your_dedicated_contact]                                                                                 NVARCHAR (1000)  NULL,
    [PM_do_you_trust_your_dedicated_contact_text]                                                                            NVARCHAR (1000)  NULL,
    [PM_does_specialist_knowledge_come_through]                                                                              NVARCHAR (1000)  NULL,
    [PM_has_service_improved_6months]                                                                                        NVARCHAR (1000)  NULL,
    [PM_has_service_improved_6months_text]                                                                                   NVARCHAR (1000)  NULL,
    [PM_is_dedicated_contact_proactive]                                                                                      NVARCHAR (1000)  NULL,
    [PM_most_valuable_part_of_membership]                                                                                    NVARCHAR (1000)  NULL,
    [PM_opt_out_of_contact_for_feedback]                                                                                     NVARCHAR (1000)  NULL,
    [NPS_Can_we_share_feedback_with_bank]                                                                                    NVARCHAR (1000)  NULL,
    [NPS_JP_use_svc_if_card_benefit_comments]                                                                                NVARCHAR (1000)  NULL,
    [Guide_score]                                                                                                            NVARCHAR (1000)  NULL,
    [NPS_JP_TypeofRequest]                                                                                                   NVARCHAR (1000)  NULL,
    [NPS_JP_use_svc_if_card_benefit]                                                                                         NVARCHAR (1000)  NULL,
    [NPS_JP_is_Ten_better_than_Platinum]                                                                                     NVARCHAR (1000)  NULL,
    [NPS_JP_is_Ten_better_than_other_svc]                                                                                    NVARCHAR (1000)  NULL
);

