CREATE TABLE [RedShift_mastercard_production].[pages] (
    [id]                       NVARCHAR (512) NULL,
    [received_at]              DATETIME2 (7)  NULL,
    [uuid]                     BIGINT         NULL,
    [context_user_agent]       NVARCHAR (512) NULL,
    [sent_at]                  DATETIME2 (7)  NULL,
    [user_id]                  NVARCHAR (512) NULL,
    [anonymous_id]             NVARCHAR (512) NULL,
    [context_page_title]       NVARCHAR (512) NULL,
    [uuid_ts]                  DATETIME2 (7)  NULL,
    [context_ip]               NVARCHAR (512) NULL,
    [context_page_url]         NVARCHAR (512) NULL,
    [original_timestamp]       DATETIME2 (7)  NULL,
    [timestamp]                DATETIME2 (7)  NULL,
    [title]                    NVARCHAR (512) NULL,
    [url]                      NVARCHAR (512) NULL,
    [context_page_path]        NVARCHAR (512) NULL,
    [name]                     NVARCHAR (512) NULL,
    [context_page_referrer]    NVARCHAR (512) NULL,
    [path]                     NVARCHAR (512) NULL,
    [referrer]                 NVARCHAR (512) NULL,
    [context_library_name]     NVARCHAR (512) NULL,
    [context_library_version]  NVARCHAR (512) NULL,
    [context_page_search]      NVARCHAR (512) NULL,
    [search]                   NVARCHAR (512) NULL,
    [context_campaign_content] NVARCHAR (512) NULL,
    [context_campaign_name]    NVARCHAR (512) NULL,
    [context_campaign_medium]  NVARCHAR (512) NULL,
    [context_campaign_source]  NVARCHAR (512) NULL,
    [context_campaign_term]    NVARCHAR (512) NULL,
    [pagesId]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_RedShift_mastercard_production_pagesId] PRIMARY KEY CLUSTERED ([pagesId] ASC)
);

