CREATE TABLE [dbo].[zzNPS_InMomentXTEN070225] (
    [NPS_InMomentId]      INT              IDENTITY (1, 1) NOT NULL,
    [Response ID]         BIGINT           NULL,
    [Member_id]           INT              NULL,
    [Response Date]       DATETIME         NULL,
    [Survey Name]         NVARCHAR (200)   NULL,
    [Scheme ID]           INT              NULL,
    [Scheme Name]         NVARCHAR (200)   NULL,
    [Data Status]         NVARCHAR (100)   NULL,
    [U ID]                NVARCHAR (100)   NULL,
    [Issuer]              INT              NULL,
    [LTR]                 INT              NULL,
    [LTR Verbatim]        NVARCHAR (MAX)   NULL,
    [CSAT]                INT              NULL,
    [CallBack]            NVARCHAR (20)    NULL,
    [Agree Attended]      INT              NULL,
    [Agree Concierge]     INT              NULL,
    [Agree EasytoGetHelp] INT              NULL,
    [Concierge Influence] NVARCHAR (100)   NULL,
    [Agree Professional]  INT              NULL,
    [Agree QuickResponse] INT              NULL,
    [Membership Type]     NVARCHAR (200)   NULL,
    [Job Vendor Name]     NVARCHAR (2000)  NULL,
    [Inserted_On]         DATETIME         NULL,
    [Filename]            NVARCHAR (200)   NULL,
    [ProcessId]           UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([NPS_InMomentId] ASC)
);

