CREATE TABLE [Genesys_ININ_DIALER_40].[CallHistory] (
    [agentid]                 VARCHAR (80)  NULL,
    [agentoverride]           SMALLINT      NULL,
    [cadetail]                VARCHAR (255) NULL,
    [callansweredtimeUTC]     DATETIME      NULL,
    [callconnectedtimeUTC]    DATETIME      NULL,
    [calldisconnectedtimeUTC] DATETIME      NOT NULL,
    [calledpartyoffset]       INT           NULL,
    [callhistory_id]          BIGINT        NOT NULL,
    [callid]                  CHAR (11)     NULL,
    [callidkey]               CHAR (18)     NULL,
    [callingmode]             TINYINT       NULL,
    [callplacedtimeUTC]       DATETIME      NULL,
    [callscheduletime]        DATETIME      NULL,
    [campaignfilterid]        SMALLINT      NULL,
    [campaignname]            VARCHAR (255) NOT NULL,
    [caresult]                TINYINT       NULL,
    [customdata1]             VARCHAR (255) NULL,
    [customdata2]             VARCHAR (255) NULL,
    [i3_identity]             BIGINT        NULL,
    [i3_rowid]                VARCHAR (80)  NULL,
    [isabandoned]             BIT           NULL,
    [isAdditionalCall]        BIT           NULL,
    [iscontact]               BIT           NULL,
    [isdetect]                BIT           NULL,
    [isrpc]                   BIT           NULL,
    [issuccess]               BIT           NULL,
    [length]                  INT           NULL,
    [messageplaytimeUTC]      DATETIME      NULL,
    [odsoffset]               INT           NOT NULL,
    [phonenumber]             VARCHAR (50)  NULL,
    [phonenumbertype]         VARCHAR (80)  NULL,
    [previewpoptimeUTC]       DATETIME      NULL,
    [previewtimerinit]        BIT           NULL,
    [rulegroupid]             SMALLINT      NULL,
    [siteid]                  VARCHAR (80)  NOT NULL,
    [successresult]           FLOAT (53)    NULL,
    [wrapupcategory]          VARCHAR (80)  NOT NULL,
    [wrapupcode]              VARCHAR (80)  NOT NULL,
    CONSTRAINT [PK_Genesys_ININ_DIALER_40_CallHistory] PRIMARY KEY CLUSTERED ([callhistory_id] ASC)
);

