CREATE TABLE [RedShift_scotia_evasion].[booking_request_event] (
    [id]                                    NVARCHAR (512) NULL,
    [received_at]                           DATETIME2 (7)  NULL,
    [uuid]                                  BIGINT         NULL,
    [request_data_extra_details]            NVARCHAR (512) NULL,
    [request_data_is_flight_briefing]       VARCHAR (5)    NULL,
    [anonymous_id]                          NVARCHAR (512) NULL,
    [request_data_num_infants]              BIGINT         NULL,
    [timestamp]                             DATETIME2 (7)  NULL,
    [context_user_agent]                    NVARCHAR (512) NULL,
    [context_page_url]                      NVARCHAR (512) NULL,
    [event]                                 NVARCHAR (512) NULL,
    [event_text]                            NVARCHAR (512) NULL,
    [request_data_flexible_on_dates]        VARCHAR (5)    NULL,
    [request_data_inbound_date]             DATETIME2 (7)  NULL,
    [request_data_preferred_contact_method] NVARCHAR (512) NULL,
    [sent_at]                               DATETIME2 (7)  NULL,
    [context_library_version]               NVARCHAR (512) NULL,
    [type]                                  NVARCHAR (512) NULL,
    [request_data_num_adults]               BIGINT         NULL,
    [user_id]                               NVARCHAR (512) NULL,
    [context_library_name]                  NVARCHAR (512) NULL,
    [request_data_is_car_hire_briefing]     VARCHAR (5)    NULL,
    [request_data_outbound_date]            DATETIME2 (7)  NULL,
    [context_ip]                            NVARCHAR (512) NULL,
    [context_page_referrer]                 NVARCHAR (512) NULL,
    [context_page_title]                    NVARCHAR (512) NULL,
    [original_timestamp]                    DATETIME2 (7)  NULL,
    [request_data_inbound_location]         NVARCHAR (512) NULL,
    [request_data_is_hotel_briefing]        VARCHAR (5)    NULL,
    [request_data_num_children]             BIGINT         NULL,
    [uuid_ts]                               DATETIME2 (7)  NULL,
    [context_page_path]                     NVARCHAR (512) NULL,
    [request_data_outbound_location]        NVARCHAR (512) NULL,
    [request_data_quantity]                 BIGINT         NULL,
    [request_data_budget]                   NVARCHAR (512) NULL,
    [request_data_ticket_type]              NVARCHAR (512) NULL,
    [request_data_restaurant]               NVARCHAR (512) NULL,
    [request_data_requested_date]           DATETIME2 (7)  NULL,
    [request_data_requested_time]           NVARCHAR (512) NULL,
    [request_data_flexible_on_times]        VARCHAR (5)    NULL,
    [request_data_dietary_requirements]     NVARCHAR (512) NULL,
    [booking_request_eventId]               BIGINT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_RedShift_scotia_evasion_booking_request_eventId] PRIMARY KEY CLUSTERED ([booking_request_eventId] ASC)
);

