CREATE TABLE [Genesys_dbo].[Contacts] (
    [Access]          INT             NULL,
    [Assistant]       NVARCHAR (64)   NULL,
    [AssistantPhone]  NVARCHAR (80)   NULL,
    [BusinessAddress] NVARCHAR (128)  NULL,
    [BusinessCity]    NVARCHAR (30)   NULL,
    [BusinessCountry] NVARCHAR (30)   NULL,
    [BusinessEMail]   NVARCHAR (128)  NULL,
    [BusinessPhone]   NVARCHAR (80)   NULL,
    [BusinessPhone2]  NVARCHAR (80)   NULL,
    [BusinessState]   NVARCHAR (6)    NULL,
    [BusinessZip]     NVARCHAR (15)   NULL,
    [Company]         NVARCHAR (64)   NULL,
    [Department]      NVARCHAR (64)   NULL,
    [Fax]             NVARCHAR (80)   NULL,
    [FirstName]       NVARCHAR (30)   NULL,
    [HomeAddress]     NVARCHAR (128)  NULL,
    [HomeCity]        NVARCHAR (30)   NULL,
    [HomeCountry]     NVARCHAR (30)   NULL,
    [HomeEMail]       NVARCHAR (128)  NULL,
    [HomePhone]       NVARCHAR (80)   NULL,
    [HomePhone2]      NVARCHAR (80)   NULL,
    [HomeState]       NVARCHAR (6)    NULL,
    [HomeZip]         NVARCHAR (15)   NULL,
    [ID]              NVARCHAR (25)   NOT NULL,
    [LastName]        NVARCHAR (30)   NULL,
    [Mobile]          NVARCHAR (80)   NULL,
    [Name]            NVARCHAR (64)   NULL,
    [Notes]           NVARCHAR (2000) NULL,
    [Owner]           NVARCHAR (50)   NULL,
    [Pager]           NVARCHAR (80)   NULL,
    [Password]        NVARCHAR (12)   NULL,
    [PrimaryNumber]   NVARCHAR (2)    NULL,
    [Title]           NVARCHAR (50)   NULL,
    [URL]             NVARCHAR (255)  NULL,
    CONSTRAINT [PK_Genesys_dbo_Contacts] PRIMARY KEY CLUSTERED ([ID] ASC)
);

