CREATE TABLE [Genesys_dbo].[FaxEnvelopeHist] (
    [CallIdKey]             CHAR (18)       NOT NULL,
    [CheapBeginDateTime]    DATETIME        NOT NULL,
    [CheapEndDateTime]      DATETIME        NOT NULL,
    [CoverPageName]         NVARCHAR (50)   NULL,
    [DeviceGroup]           NVARCHAR (50)   NULL,
    [Direction]             TINYINT         NOT NULL,
    [Duration]              INT             NOT NULL,
    [EnvelopeId]            BIGINT          NOT NULL,
    [EnvelopeTimeStamp]     INT             NOT NULL,
    [ErrorInfo]             NVARCHAR (1024) NULL,
    [FailureAddress]        VARCHAR (1024)  NULL,
    [FailureAttempts]       INT             NOT NULL,
    [FailureType]           INT             NOT NULL,
    [FaxComment]            NVARCHAR (1024) NULL,
    [FaxId]                 BIGINT          NOT NULL,
    [FaxTimeStamp]          INT             NOT NULL,
    [FromCompany]           NVARCHAR (50)   NULL,
    [FromFaxPhone]          NVARCHAR (50)   NULL,
    [FromName]              NVARCHAR (50)   NULL,
    [FromVoicePhone]        NVARCHAR (50)   NULL,
    [Header]                VARCHAR (128)   NULL,
    [I3TimeStampGMT]        DATETIME        NOT NULL,
    [LineNoise]             INT             NOT NULL,
    [LocalCSId]             NVARCHAR (50)   NULL,
    [MaxBPS]                INT             NOT NULL,
    [NotifyOnFailure]       INT             NOT NULL,
    [NotifyOnSuccess]       INT             NOT NULL,
    [PageCount]             INT             NOT NULL,
    [PortName]              NVARCHAR (50)   NULL,
    [PortNumber]            INT             NOT NULL,
    [ProcessingDateTime]    DATETIME        NOT NULL,
    [ProcessingDateTimeGmt] DATETIME        NOT NULL,
    [RemoteCSId]            VARCHAR (50)    NULL,
    [RemoteNumber]          VARCHAR (50)    NULL,
    [Retries]               INT             NOT NULL,
    [RetryDelay]            INT             NOT NULL,
    [ScheduledDateTime]     DATETIME        NOT NULL,
    [SenderName]            NVARCHAR (50)   NULL,
    [SendWhen]              INT             NOT NULL,
    [SignalQuality]         INT             NOT NULL,
    [SignalStrength]        INT             NOT NULL,
    [SiteId]                SMALLINT        NOT NULL,
    [Speed]                 INT             NOT NULL,
    [SubmitDateTime]        DATETIME        NOT NULL,
    [SubmitDateTimeGMT]     DATETIME        NOT NULL,
    [SubSiteId]             SMALLINT        NOT NULL,
    [SuccessAddress]        VARCHAR (1024)  NULL,
    [SuccessFlag]           CHAR (1)        NOT NULL,
    [T30]                   VARCHAR (50)    NULL,
    [ToCompany]             NVARCHAR (50)   NULL,
    [ToName]                NVARCHAR (50)   NULL,
    [ToVoicePhone]          NVARCHAR (50)   NULL,
    CONSTRAINT [PK_Genesys_dbo_FaxEnvelopeHist] PRIMARY KEY CLUSTERED ([CallIdKey] ASC, [EnvelopeId] ASC, [EnvelopeTimeStamp] ASC, [SiteId] ASC)
);

