CREATE TABLE [Genesys_dbo].[Individual] (
    [Active]          TINYINT        NOT NULL,
    [AppIndivID]      NVARCHAR (255) NULL,
    [AssistantName]   NVARCHAR (100) NULL,
    [Company]         NVARCHAR (100) NULL,
    [Department]      NVARCHAR (50)  NULL,
    [ExtID]           NVARCHAR (255) NULL,
    [ExtSource]       NVARCHAR (64)  NULL,
    [FirstName]       NVARCHAR (50)  NULL,
    [ICUserID]        NVARCHAR (50)  NULL,
    [IndivID]         CHAR (22)      NOT NULL,
    [IndivImage]      NVARCHAR (255) NULL,
    [IndivTypeID]     INT            NOT NULL,
    [IndivURL]        NVARCHAR (255) NULL,
    [IsPrivate]       TINYINT        NOT NULL,
    [JobTitle]        NVARCHAR (100) NULL,
    [LastName]        NVARCHAR (50)  NULL,
    [LocID]           CHAR (22)      NULL,
    [MiddleName]      NVARCHAR (50)  NULL,
    [ModifyDateTime]  DATETIME2 (7)  NULL,
    [OrgID]           CHAR (22)      NULL,
    [OwnerID]         NVARCHAR (50)  NULL,
    [SiteID]          SMALLINT       NULL,
    [TitleID]         INT            NULL,
    [UserSecChecksum] INT            NULL,
    [Version]         INT            NOT NULL,
    [WebLogin]        NVARCHAR (100) NULL,
    [WebPassword]     NVARCHAR (64)  NULL,
    [WebPasswordKey]  TINYINT        NULL,
    CONSTRAINT [PK_Genesys_dbo_Individual] PRIMARY KEY CLUSTERED ([IndivID] ASC)
);

