CREATE TABLE [Genesys_dbo].[InteractionSummary_Static] (
    [AccountCode]              NVARCHAR (50)   NULL,
    [CallEventLog]             NVARCHAR (MAX)  NULL,
    [CallNote]                 NVARCHAR (1024) NULL,
    [ConnectedDateTimeUTC]     DATETIME2 (7)   NOT NULL,
    [ConnectionType]           TINYINT         NOT NULL,
    [Direction]                TINYINT         NOT NULL,
    [Disposition]              TINYINT         NOT NULL,
    [DispositionCode]          TINYINT         NULL,
    [DNIS_LocalID]             NVARCHAR (50)   NULL,
    [FirstAssignedAcdSkillSet] NVARCHAR (100)  NULL,
    [IndivID]                  CHAR (22)       NULL,
    [InitiatedDateTimeUTC]     DATETIME2 (7)   NOT NULL,
    [InteractionID]            BIGINT          NOT NULL,
    [InteractionIDKey]         CHAR (18)       NOT NULL,
    [IsRecorded]               BIT             NULL,
    [IsSurveyed]               BIT             NULL,
    [LastAssignedWorkgroupID]  NVARCHAR (100)  NULL,
    [LastLocalName]            NVARCHAR (50)   NULL,
    [LastLocalNumber]          VARCHAR (200)   NULL,
    [LastLocalUserId]          NVARCHAR (50)   NULL,
    [LastStationId]            NVARCHAR (50)   NULL,
    [LineDuration]             NUMERIC (18)    NULL,
    [LineId]                   NVARCHAR (50)   NULL,
    [MediaServerID]            NVARCHAR (100)  NULL,
    [MediaType]                TINYINT         NOT NULL,
    [nConference]              SMALLINT        NULL,
    [nExternal]                SMALLINT        NULL,
    [nHeld]                    SMALLINT        NULL,
    [nIVR]                     SMALLINT        NULL,
    [nPark]                    SMALLINT        NULL,
    [nQueueWait]               SMALLINT        NULL,
    [nSecuredIVR]              SMALLINT        NOT NULL,
    [nTalk]                    SMALLINT        NULL,
    [nTransfer]                SMALLINT        NULL,
    [OrgID]                    CHAR (22)       NULL,
    [PurposeCode]              INT             NULL,
    [RemoteICUserID]           INT             NULL,
    [RemoteID]                 INT             NULL,
    [RemoteName]               INT             NULL,
    [RemoteNumberCallId]       INT             NULL,
    [RemoteNumberCountry]      INT             NULL,
    [RemoteNumberFmt]          INT             NULL,
    [RemoteNumberLoComp1]      INT             NULL,
    [RemoteNumberLoComp2]      INT             NULL,
    [SeqNo]                    TINYINT         NOT NULL,
    [SiteID]                   SMALLINT        NOT NULL,
    [StartDateTimeUTC]         DATETIME2 (7)   NOT NULL,
    [StartDTOffset]            INT             NOT NULL,
    [tACW]                     INT             NULL,
    [tAlert]                   INT             NULL,
    [tConference]              NUMERIC (18)    NULL,
    [tConnected]               NUMERIC (18)    NULL,
    [tDialing]                 INT             NULL,
    [TerminatedDateTimeUTC]    DATETIME2 (7)   NOT NULL,
    [tExternal]                NUMERIC (18)    NULL,
    [tHeld]                    NUMERIC (18)    NULL,
    [tIVRWait]                 INT             NULL,
    [tPark]                    NUMERIC (18)    NULL,
    [tQueueWait]               NUMERIC (18)    NULL,
    [tSecuredIVR]              NUMERIC (18)    NULL,
    [tSuspend]                 NUMERIC (18)    NULL,
    [WrapUpCode]               NVARCHAR (200)  NULL
);

