CREATE TABLE [Genesys_dbo].[IO_Agent] (
    [AccrualReferenceDate]       DATETIME       NULL,
    [AgentGroupID]               CHAR (22)      NULL,
    [AgentID]                    CHAR (22)      NOT NULL,
    [AgentRank]                  INT            NULL,
    [CoverageGroupID]            CHAR (22)      NULL,
    [DataNeedsReview]            TINYINT        NULL,
    [DesiredMaximumPaidTime]     INT            NULL,
    [EndDate]                    DATETIME       NULL,
    [HasConfiguration]           TINYINT        NOT NULL,
    [MaximumDays]                INT            NULL,
    [MaximumPaidTime]            INT            NULL,
    [MinimumInterShiftTime]      INT            NULL,
    [MinimumPaidTime]            INT            NULL,
    [ModifierUserID]             NVARCHAR (100) NULL,
    [ModifyDateTimeUTC]          DATETIME       NULL,
    [PreferenceToCoverage]       TINYINT        NULL,
    [RotationStartDate]          DATETIME       NULL,
    [RotationStartShiftDefIndex] INT            NULL,
    [RotationStopDate]           DATETIME       NULL,
    [ScheduleBidding]            TINYINT        NULL,
    [ShiftDefinitionID]          CHAR (22)      NULL,
    [ShiftRotationID]            CHAR (22)      NULL,
    [SiteID]                     INT            NULL,
    [StartDate]                  DATETIME       NULL,
    [TeamID]                     CHAR (22)      NULL,
    [TimeZoneID]                 NVARCHAR (100) NULL,
    [UseDesiredMaximumPaidTime]  TINYINT        NULL,
    [UseMaximumDays]             TINYINT        NULL,
    [UseMaximumPaidTime]         TINYINT        NULL,
    [UseMinimumInterShiftTime]   TINYINT        NULL,
    [UseMinimumPaidTime]         TINYINT        NULL,
    [UserName]                   NVARCHAR (100) NOT NULL,
    [Version]                    INT            NOT NULL,
    CONSTRAINT [PK_Genesys_dbo_IO_Agent] PRIMARY KEY CLUSTERED ([AgentID] ASC)
);

