CREATE TABLE [Genesys_dbo].[IO_SchedulingUnit] (
    [ActivityBidding]                TINYINT        NULL,
    [AdherenceAutoExcuseSecs]        INT            NOT NULL,
    [AdherenceTreatNonAcdEquivalent] TINYINT        NOT NULL,
    [ConformanceActivities]          INT            NULL,
    [ConformanceUseOnlyPaid]         TINYINT        NOT NULL,
    [DailyFTEHours]                  NUMERIC (18)   NOT NULL,
    [EnableShiftTrading]             TINYINT        NOT NULL,
    [IntervalShrinkage]              VARCHAR (MAX)  NULL,
    [IsActive]                       TINYINT        NOT NULL,
    [LastSimActualUpdateDateTimeUTC] DATETIME       NULL,
    [LastUpdateDateTimeUTC]          DATETIME       NULL,
    [MaximumFullDayTimeOffHours]     NUMERIC (18)   NULL,
    [MaximumPartialDayTimeOffHours]  NUMERIC (18)   NULL,
    [MaxOccupancy]                   TINYINT        NOT NULL,
    [MinDayContigHrsAfterTrade]      INT            NOT NULL,
    [MinimumFullDayTimeOffHours]     NUMERIC (18)   NULL,
    [MinimumPartialDayTimeOffHours]  NUMERIC (18)   NULL,
    [MinTradeFutureHours]            INT            NOT NULL,
    [MinTradeLengthHours]            INT            NOT NULL,
    [ModifierUserID]                 NVARCHAR (100) NULL,
    [ModifyDateTimeUTC]              DATETIME       NULL,
    [OccurrencesToImport]            TINYINT        NOT NULL,
    [PartialTradeNeedsReview]        TINYINT        NOT NULL,
    [PerDayShrinkage]                NVARCHAR (MAX) NULL,
    [PreferenceToCoverage]           TINYINT        NULL,
    [PurgeExpiredTradesDaysOld]      INT            NOT NULL,
    [SchedulingUnitID]               CHAR (22)      NOT NULL,
    [SchedulingUnitName]             NVARCHAR (100) NOT NULL,
    [ShrinkageFactor]                NUMERIC (18)   NOT NULL,
    [StartDayOfWeek]                 INT            NOT NULL,
    [TimeZoneID]                     NVARCHAR (100) NULL,
    [TradeMatchWindowHours]          INT            NOT NULL,
    [TradingMatchCriteria]           INT            NOT NULL,
    [UseOccurrencesToImport]         TINYINT        NOT NULL,
    [UseWeeksToImport]               TINYINT        NOT NULL,
    [Version]                        INT            NOT NULL,
    [WeeklyFTEHours]                 NUMERIC (18)   NOT NULL,
    [WeeksToImport]                  TINYINT        NOT NULL,
    [WeeksToUseForLTFStaffing]       TINYINT        NOT NULL,
    CONSTRAINT [PK_Genesys_dbo_IO_SchedulingUnit] PRIMARY KEY CLUSTERED ([SchedulingUnitID] ASC)
);

