CREATE TABLE [Genesys_dbo].[IR_QForm] (
    [AssignedDesc]                NVARCHAR (1024)  NULL,
    [CriticalAccuracyScore]       NUMERIC (18)     NULL,
    [IsFailed]                    TINYINT          NULL,
    [MaxScore]                    NUMERIC (18)     NULL,
    [MinScore]                    NUMERIC (18)     NULL,
    [NonCriticalMaxScore]         NUMERIC (18)     NULL,
    [NonCriticalMinScore]         NUMERIC (18)     NULL,
    [NonCriticalScore]            NUMERIC (18)     NULL,
    [NumAnsweredCriticalQstns]    INT              NULL,
    [NumPosAnsweredCriticalQstns] INT              NULL,
    [QFormId]                     UNIQUEIDENTIFIER NOT NULL,
    [QuestionnaireId]             UNIQUEIDENTIFIER NOT NULL,
    [RankName]                    NVARCHAR (40)    NULL,
    [RecordingId]                 UNIQUEIDENTIFIER NULL,
    [Score]                       NUMERIC (18)     NOT NULL,
    [ScoringDate]                 DATETIME         NULL,
    [ScoringDateOffset]           INT              NULL,
    [ScoringIndivId]              CHAR (22)        NULL,
    [ScoringState]                INT              NOT NULL,
    [SignoffComments]             NVARCHAR (2000)  NULL,
    [SignoffState]                TINYINT          NULL,
    [TargetIndivId]               CHAR (22)        NULL,
    [TargetIntx_Part_Id]          CHAR (22)        NULL,
    [UsingForCalibration]         TINYINT          NOT NULL,
    [Version]                     INT              NOT NULL,
    [Workgroup]                   NVARCHAR (255)   NULL,
    CONSTRAINT [PK_Genesys_dbo_IR_QForm] PRIMARY KEY CLUSTERED ([QFormId] ASC)
);

