CREATE TABLE [Genesys_dbo].[RPT_parameters] (
    [allow_and]                  BIT              NOT NULL,
    [allow_or]                   BIT              NOT NULL,
    [allow_sample]               BIT              NOT NULL,
    [assembly_name]              VARCHAR (255)    NOT NULL,
    [class_name]                 VARCHAR (255)    NOT NULL,
    [column_name]                NVARCHAR (50)    NULL,
    [column_name2]               NVARCHAR (50)    NULL,
    [convert_date_to_utc]        SMALLINT         NOT NULL,
    [custom_data_1]              NVARCHAR (2048)  NULL,
    [custom_data_2]              NVARCHAR (2048)  NULL,
    [custom_data_3]              NVARCHAR (2048)  NULL,
    [data_type]                  INT              NOT NULL,
    [default_value]              NVARCHAR (1024)  NULL,
    [description]                NVARCHAR (1024)  NULL,
    [description_resource]       NVARCHAR (1024)  NULL,
    [display_by_default]         SMALLINT         NOT NULL,
    [friendly_key]               NVARCHAR (50)    NULL,
    [is_required]                BIT              NOT NULL,
    [is_visible]                 BIT              NOT NULL,
    [last_modified_dateUTC]      DATETIME2 (7)    NOT NULL,
    [license]                    NVARCHAR (500)   NULL,
    [name]                       NVARCHAR (50)    NOT NULL,
    [name_resource]              NVARCHAR (50)    NULL,
    [parameter_id]               UNIQUEIDENTIFIER NOT NULL,
    [parameter_type]             INT              NOT NULL,
    [report_id]                  UNIQUEIDENTIFIER NOT NULL,
    [seqno]                      TINYINT          NOT NULL,
    [source]                     INT              NOT NULL,
    [user_control_assembly_name] VARCHAR (255)    NULL,
    [user_control_class_name]    VARCHAR (255)    NULL,
    [version]                    SMALLINT         NOT NULL,
    CONSTRAINT [PK_Genesys_dbo_RPT_parameters] PRIMARY KEY CLUSTERED ([parameter_id] ASC)
);

