CREATE TABLE [Genesys_dbo].[RPT_reports] (
    [allow_count]            BIT              NOT NULL,
    [allow_parameter_edit]   BIT              NOT NULL,
    [assembly_name]          NVARCHAR (100)   NULL,
    [category_id]            UNIQUEIDENTIFIER NOT NULL,
    [class_name]             NVARCHAR (100)   NULL,
    [description]            NVARCHAR (1024)  NULL,
    [description_resource]   NVARCHAR (1024)  NULL,
    [ds_key]                 INT              NOT NULL,
    [friendly_key]           NVARCHAR (1024)  NULL,
    [ic_datasource]          NVARCHAR (100)   NULL,
    [is_locked]              BIT              NOT NULL,
    [is_released]            BIT              NOT NULL,
    [is_visible]             BIT              NOT NULL,
    [last_modified_dateUTC]  DATETIME2 (7)    NOT NULL,
    [last_run_date_time_UTC] DATETIME2 (7)    NULL,
    [last_run_user_id]       NVARCHAR (50)    NULL,
    [license]                NVARCHAR (500)   NULL,
    [linked_report_fk]       NVARCHAR (50)    NULL,
    [logo_file]              NVARCHAR (1024)  NULL,
    [maximum_rows]           INT              NOT NULL,
    [name]                   NVARCHAR (1024)  NOT NULL,
    [name_resource]          NVARCHAR (1024)  NULL,
    [notes]                  NVARCHAR (2048)  NULL,
    [orientation]            INT              NOT NULL,
    [param_page_help_id]     NVARCHAR (5)     NULL,
    [report_filename]        NVARCHAR (MAX)   NULL,
    [report_id]              UNIQUEIDENTIFIER NOT NULL,
    [report_page_help_id]    NVARCHAR (5)     NULL,
    [report_type]            INT              NOT NULL,
    [report_xml]             NVARCHAR (2048)  NULL,
    [require_acl]            BIT              NOT NULL,
    [run_count]              INT              NOT NULL,
    [seqno]                  TINYINT          NOT NULL,
    [stored_procedure]       NVARCHAR (60)    NULL,
    [stored_procedure_count] NVARCHAR (60)    NULL,
    [stored_procedure_samp]  NVARCHAR (60)    NULL,
    [subtitle]               NVARCHAR (50)    NULL,
    [subtitle_resource]      NVARCHAR (50)    NULL,
    [timeout_period]         INT              NOT NULL,
    [version]                SMALLINT         NOT NULL,
    CONSTRAINT [PK_Genesys_dbo_RPT_reports] PRIMARY KEY CLUSTERED ([report_id] ASC)
);

