CREATE TABLE [Genesys_dbo].[SegmentExceptions] (
    [Abandoned]        BIT            NOT NULL,
    [AgentAbandoned]   BIT            NOT NULL,
    [AgentFlowout]     BIT            NOT NULL,
    [AgentQueue]       NVARCHAR (50)  NULL,
    [Answered]         BIT            NOT NULL,
    [Destination]      NVARCHAR (100) NULL,
    [Direction]        TINYINT        NOT NULL,
    [Flowin]           BIT            NOT NULL,
    [Flowout]          BIT            NOT NULL,
    [id]               BIGINT         NOT NULL,
    [InteractionIDKey] CHAR (18)      NOT NULL,
    [MediaType]        TINYINT        NOT NULL,
    [RemoteName]       NVARCHAR (50)  NULL,
    [RemoteNumber]     VARCHAR (50)   NULL,
    [SegNo]            SMALLINT       NOT NULL,
    [SiteID]           SMALLINT       NOT NULL,
    [SkillSet]         NVARCHAR (100) NULL,
    [Source]           NVARCHAR (100) NULL,
    [t2ndWait]         NUMERIC (18)   NULL,
    [tInQueue]         NUMERIC (18)   NOT NULL,
    [Transferin]       BIT            NOT NULL,
    [Transferout]      BIT            NOT NULL,
    [tsAlertAgent]     DATETIME2 (7)  NULL,
    [tsEnterQueue]     DATETIME2 (7)  NOT NULL,
    [tsException]      DATETIME2 (7)  NULL,
    [tWait]            NUMERIC (18)   NOT NULL,
    [WorkgroupQueue]   NVARCHAR (100) NULL,
    CONSTRAINT [PK_Genesys_dbo_SegmentExceptions] PRIMARY KEY CLUSTERED ([id] ASC)
);

