CREATE TABLE [Genesys_dbo].[SR_AutomatedReports] (
    [AccessLvl]              NVARCHAR (25)   NULL,
    [Active]                 BIT             NOT NULL,
    [Description]            NVARCHAR (MAX)  NULL,
    [DTParameterNames]       NVARCHAR (255)  NULL,
    [DTParameterValues]      NVARCHAR (255)  NULL,
    [EmailAddresses]         NVARCHAR (1028) NULL,
    [EmailReportFormat]      NVARCHAR (50)   NULL,
    [EndDateTime]            DATETIME        NULL,
    [FileLocations]          NVARCHAR (1028) NULL,
    [FileOverwriteFrequency] NVARCHAR (20)   NULL,
    [FileReportFormat]       NVARCHAR (50)   NULL,
    [Frequency]              NVARCHAR (30)   NULL,
    [LastFrequency]          DATETIME        NULL,
    [LastUpdate]             DATETIME        NULL,
    [LastUpdateBy]           NVARCHAR (50)   NULL,
    [Modified]               BIT             NULL,
    [Name]                   NVARCHAR (100)  NOT NULL,
    [NumericParameterNames]  NVARCHAR (255)  NULL,
    [NumericParameterValues] NVARCHAR (MAX)  NULL,
    [Password]               NVARCHAR (50)   NULL,
    [Period]                 NVARCHAR (30)   NULL,
    [PrinterNames]           NVARCHAR (1028) NULL,
    [ReportName]             NVARCHAR (100)  NULL,
    [ReportType]             NVARCHAR (50)   NULL,
    [ReportXML]              NVARCHAR (MAX)  NULL,
    [ScheduledReportId]      INT             NOT NULL,
    [ScheduledTime]          NVARCHAR (5)    NULL,
    [Server]                 NVARCHAR (50)   NULL,
    [SiteName]               NVARCHAR (25)   NOT NULL,
    [StartDateTime]          DATETIME        NULL,
    [StringParameterNames]   NVARCHAR (255)  NULL,
    [StringParameterValues]  NVARCHAR (MAX)  NULL,
    [Username]               NVARCHAR (50)   NULL
);

