CREATE USER [TENUK\DB_LDCSQLPD22_TenDataWarehouse_Internal_QA_RO] FOR LOGIN [TENUK\DB_LDCSQLPD22_TenDataWarehouse_Internal_QA_RO]
    WITH DEFAULT_SCHEMA = [TENUK\DB_LDCSQLPD22_TenDataWarehouse_Internal_QA_RO];

