CREATE TABLE [TenMAID_Global].[CorporateScheme_Staging] (
    [AccountManagerID]          INT            NULL,
    [Alert]                     NTEXT          NULL,
    [AlternateName]             NVARCHAR (100) NULL,
    [CompanyGroup]              NVARCHAR (50)  NULL,
    [CompanyName]               NVARCHAR (100) NULL,
    [CorporateEmail]            VARCHAR (255)  NULL,
    [CorporateMessage]          NTEXT          NULL,
    [CorporateSchemeID]         INT            NOT NULL,
    [CorporateshipStatusID]     INT            NULL,
    [CreatedBy]                 INT            NULL,
    [CurrencyID]                INT            NULL,
    [DateCreated]               DATETIME       NULL,
    [DateUpdated]               DATETIME       NULL,
    [DolphinZoneID]             INT            NULL,
    [IATANumber]                VARCHAR (30)   NULL,
    [InvoicedByFinance]         INT            NULL,
    [IsAddressMandatory]        BIT            NULL,
    [IsColdWarmTrans]           BIT            NULL,
    [IsCorpEmail]               BIT            NULL,
    [IsJobCountRestriction]     BIT            NULL,
    [IsJobRestrictionRecurring] BIT            NULL,
    [IsJobsUrgent]              BIT            NULL,
    [IsNewsLetter]              BIT            NULL,
    [IsRestrictiononSchemeDate] BIT            NULL,
    [IsWhiteLabelled]           SMALLINT       NULL,
    [JobAllowance]              INT            NULL,
    [LaunchDate]                DATETIME       NULL,
    [MainClientContact]         NVARCHAR (100) NULL,
    [MainTelephone]             NVARCHAR (50)  NULL,
    [MasterGroupId]             INT            NULL,
    [MemberPropose]             BIT            NULL,
    [Name]                      NVARCHAR (100) NULL,
    [OperationalRegionID]       INT            NULL,
    [ReceiveMail]               BIT            NULL,
    [RestrictionDate]           DATETIME       NULL,
    [SchemeEmail]               VARCHAR (255)  NULL,
    [SchemeTypeID]              SMALLINT       NULL,
    [SchemeVatTypeID]           INT            NULL,
    [TenmaidUSA]                BIT            NULL,
    [TenUKOwnerID]              INT            NULL,
    [TerminationDate]           DATETIME       NULL,
    [UpdatedBy]                 INT            NULL,
    [UsagePeriod]               INT            NULL,
    [VDN]                       CHAR (10)      NULL,
    [WebAddress]                NVARCHAR (100) NULL,
    [SYS_CHANGE_OPERATION]      NVARCHAR (1)   NULL,
    [SYS_CHANGE_VERSION]        BIGINT         NULL,
    [CallInitiator]             CHAR (20)      NULL,
    CONSTRAINT [PK_TenMAID_Global_CorporateScheme_Staging] PRIMARY KEY CLUSTERED ([CorporateSchemeID] ASC)
);

