CREATE TABLE [TenMAID_Global].[JobInvoice] (
    [Address]                     NVARCHAR (250) NULL,
    [CreatedBy]                   INT            NULL,
    [CreatedDate]                 DATETIME       NULL,
    [CurrencyID]                  INT            NOT NULL,
    [EmailID]                     NVARCHAR (100) NULL,
    [FaxNo]                       NVARCHAR (50)  NULL,
    [InvoiceAttachmentID]         INT            NULL,
    [InvoicedMethod]              INT            NULL,
    [InvoiceLocationID]           INT            NOT NULL,
    [InvoiceSendDate]             DATETIME       NULL,
    [InvoiceToName]               NVARCHAR (50)  NULL,
    [InvoiceValue]                MONEY          NOT NULL,
    [InvoiceValueInOtherCurrency] MONEY          NULL,
    [InvoiceVAT]                  FLOAT (53)     NOT NULL,
    [InvoiceVATInOtherCurrency]   FLOAT (53)     NULL,
    [IsInvoiceSend]               BIT            NOT NULL,
    [IsMultipleInvoice]           BIT            NOT NULL,
    [IsUploadedToSun]             BIT            NULL,
    [JobInvoiceID]                INT            NOT NULL,
    [ParentInvoiceID]             INT            NULL,
    [SupplierID]                  INT            NULL,
    [SupplierInvoiceID]           INT            NULL,
    [TotalInvoice]                MONEY          NOT NULL,
    [TotalInvoiceInOtherCurrency] MONEY          NULL,
    [uploadtosundate]             DATETIME       NULL,
    [VendorID]                    INT            NULL,
    CONSTRAINT [PK_TenMAID_Global_JobInvoice] PRIMARY KEY CLUSTERED ([JobInvoiceID] ASC)
);

