CREATE TABLE [TenMAID_Global].[PVTMemberPayments_Staging] (
    [PvtMemPayID]             INT             NOT NULL,
    [SupInvoiceID]            INT             NULL,
    [PaymentTypeID]           INT             NULL,
    [ChargeTypeID]            INT             NULL,
    [JobID]                   INT             NULL,
    [SupplierID]              INT             NULL,
    [MemberID]                INT             NULL,
    [DateReceived]            DATETIME        NULL,
    [CurrencyID]              INT             NULL,
    [PvtCorSchCurID]          INT             NULL,
    [Description]             NVARCHAR (250)  NULL,
    [Amount]                  MONEY           NULL,
    [AmountInRequestCurrency] MONEY           NULL,
    [AmountInGBP]             MONEY           NULL,
    [IsSaveCard]              BIT             NULL,
    [IsPaymentReceived]       BIT             NULL,
    [DateCreated]             DATETIME        NULL,
    [DateUpdated]             DATETIME        NULL,
    [CreatedBy]               INT             NULL,
    [UpdatedBy]               INT             NULL,
    [IsNewCard]               BIT             NULL,
    [issenttosun]             BIT             NULL,
    [VendorID]                INT             NULL,
    [IsAuthorise]             BIT             NULL,
    [NVC]                     VARCHAR (4)     NULL,
    [PvtCarCatID]             INT             NULL,
    [uploadtosundate]         DATETIME        NULL,
    [RealexMessage]           NVARCHAR (2000) NULL,
    [RealexReturns]           NVARCHAR (2000) NULL,
    [PvtAuthExpTypID]         INT             NULL,
    [IngenicoOrderID]         VARCHAR (100)   NULL,
    [PaymentGatwayID]         INT             NULL,
    [AuthorizationCode]       VARCHAR (50)    NULL,
    [PSPID]                   VARCHAR (30)    NULL,
    [SYS_CHANGE_OPERATION]    NVARCHAR (1)    NULL,
    [SYS_CHANGE_VERSION]      BIGINT          NULL,
    CONSTRAINT [PK_TenMAID_Global_PVTMemberPayments_Staging] PRIMARY KEY CLUSTERED ([PvtMemPayID] ASC)
);

