CREATE TABLE [TenMAID_Global].[PVTSupplierPayments_Staging] (
    [BalanceDue]                          MONEY           NULL,
    [BalanceDueInGBP]                     MONEY           NULL,
    [BalanceDueInRequestCurrency]         MONEY           NULL,
    [BookingReference]                    NVARCHAR (30)   NULL,
    [Comments]                            NVARCHAR (1000) NULL,
    [CreatedBy]                           INT             NULL,
    [CurrencyID]                          INT             NULL,
    [DateBalanceDue]                      DATETIME        NULL,
    [DateCreated]                         DATETIME        NULL,
    [DateDepositDue]                      DATETIME        NULL,
    [DateReceived]                        DATETIME        NULL,
    [DateUpdated]                         DATETIME        NULL,
    [DepartureDate]                       DATETIME        NULL,
    [DepositDue]                          MONEY           NULL,
    [DepositDueInGBP]                     MONEY           NULL,
    [DepositDueInRequestCurrency]         MONEY           NULL,
    [DiscountGivenByTen]                  MONEY           NULL,
    [DiscountGivenByTenInGBP]             MONEY           NULL,
    [DiscountGivenByTenInRequestCurrency] MONEY           NULL,
    [InvoiceDate]                         DATETIME        NULL,
    [InvoiceNumber]                       NVARCHAR (15)   NULL,
    [IsPaymentSent]                       BIT             NULL,
    [IsPaymentSentToFinance]              BIT             NULL,
    [issenttosun]                         BIT             NULL,
    [JobID]                               INT             NULL,
    [NetAmount]                           MONEY           NULL,
    [NetAmountInGBP]                      MONEY           NULL,
    [NetAmountInRequestCurrency]          MONEY           NULL,
    [PaymentTypeID]                       INT             NULL,
    [PvtSupPayID]                         INT             NOT NULL,
    [SupplierID]                          INT             NULL,
    [TotalAmount]                         MONEY           NULL,
    [TotalAmountInGBP]                    MONEY           NULL,
    [TotalAmountInRequestCurrency]        MONEY           NULL,
    [TourOperatorPrice]                   MONEY           NULL,
    [TourOperatorPriceInGBP]              MONEY           NULL,
    [TourOperatorPriceInRequestCurrency]  MONEY           NULL,
    [TransferJobID]                       INT             NULL,
    [UkVatAmount]                         MONEY           NULL,
    [UkVatAmountInGBP]                    MONEY           NULL,
    [UkVatAmountInRequestCurrency]        MONEY           NULL,
    [UpdatedBy]                           INT             NULL,
    [uploadtosundate]                     DATETIME        NULL,
    [VendorID]                            INT             NULL,
    [SYS_CHANGE_OPERATION]                NVARCHAR (1)    NULL,
    [SYS_CHANGE_VERSION]                  BIGINT          NULL,
    CONSTRAINT [PK_TenMAID_Global_PVTSupplierPayments_Staging] PRIMARY KEY CLUSTERED ([PvtSupPayID] ASC)
);

