CREATE TABLE [TenMAID_Global].[SupInvoiceItems_Staging] (
    [ActualCommission]                    MONEY         NULL,
    [AmountInRequestCurrency]             MONEY         NULL,
    [ComissionVAT]                        FLOAT (53)    NULL,
    [CommisionInOtherCurrency]            MONEY         NULL,
    [Commission]                          FLOAT (53)    NULL,
    [CommissionableAmountInGBP]           MONEY         NULL,
    [CommissionableAmountInOtherCurrency] MONEY         NULL,
    [CurrencyID]                          INT           NULL,
    [GrossSaleInCurrency]                 MONEY         NULL,
    [InvoiceTypeID]                       INT           NULL,
    [IsActualPaymentReceived]             BIT           NULL,
    [IsCommissionable]                    BIT           NULL,
    [IsDeleted]                           BIT           NULL,
    [IsSageDataUpdated]                   BIT           NULL,
    [IsSupplierUKBased]                   BIT           NULL,
    [IsUP]                                BIT           NULL,
    [IsVATIncluded]                       BIT           NULL,
    [IsVATIncludedONJobCost]              BIT           NULL,
    [JobCommission]                       MONEY         NULL,
    [JobCost]                             MONEY         NULL,
    [SageAmount]                          MONEY         NULL,
    [SageCommission]                      MONEY         NULL,
    [SageInvoiceID]                       NVARCHAR (50) NULL,
    [SupInvoiceID]                        INT           NULL,
    [SupInvoiceItemID]                    INT           NOT NULL,
    [TotalInvoiceInGBP]                   MONEY         NULL,
    [TotalInvoiceInOtherCurrency]         MONEY         NULL,
    [TotalPaidInGBP]                      MONEY         NULL,
    [TotalPaidInOtherCurrency]            MONEY         NULL,
    [VAT]                                 FLOAT (53)    NULL,
    [VATAmountInGBP]                      MONEY         NULL,
    [VATAmountInRequestCurrency]          MONEY         NULL,
    [SYS_CHANGE_OPERATION]                NVARCHAR (1)  NULL,
    [SYS_CHANGE_VERSION]                  BIGINT        NULL,
    CONSTRAINT [PK_TenMAID_Global_SupInvoiceItems_Staging] PRIMARY KEY CLUSTERED ([SupInvoiceItemID] ASC)
);

