CREATE TABLE [TenMAID_Global].[Tbl_JobVendors_Staging] (
    [ActualCommission]          MONEY          NULL,
    [ActualCost]                MONEY          NULL,
    [BookingRefNo]              NVARCHAR (200) NULL,
    [BranchID]                  INT            NULL,
    [CardType]                  INT            NULL,
    [Certainty]                 INT            NULL,
    [ChargeInvoice]             BIT            NULL,
    [ChaseCount]                INT            NULL,
    [Commission]                MONEY          NULL,
    [Commission_ISO_CurrencyID] NCHAR (6)      NULL,
    [CommissionDue]             BIT            NULL,
    [CommissionPercentage]      FLOAT (53)     NULL,
    [CommissionValue]           MONEY          NULL,
    [Cost]                      MONEY          NULL,
    [Cost_ISO_CurrencyID]       NVARCHAR (6)   NULL,
    [Disputed]                  BIT            NULL,
    [DisputeTrackID]            INT            NULL,
    [EstBookingValue]           INT            NULL,
    [EstSupRevenue]             INT            NULL,
    [ExpiryDate]                DATETIME       NULL,
    [HaveCommission]            SMALLINT       NULL,
    [InNewInvoice]              BIT            NULL,
    [InvoiceAttached]           BIT            NULL,
    [InvoiceComplete]           BIT            NULL,
    [IsInformation]             BIT            NULL,
    [IsSelected]                BIT            NULL,
    [JobDescription]            NVARCHAR (250) NULL,
    [JobID]                     INT            NULL,
    [JobVendorsID]              INT            NOT NULL,
    [LastChaseDate]             DATETIME       NULL,
    [MemberPaid]                BIT            NULL,
    [NoOfBooking]               INT            NULL,
    [PayImmediately]            BIT            NULL,
    [PaymentProbID]             INT            NULL,
    [PaymentProcID]             INT            NULL,
    [RaisedInvoice]             BIT            NULL,
    [Used]                      BIT            NULL,
    [VAT]                       BIT            NULL,
    [VendorID]                  INT            NULL,
    [SYS_CHANGE_OPERATION]      NVARCHAR (1)   NULL,
    [SYS_CHANGE_VERSION]        BIGINT         NULL,
    CONSTRAINT [PK_TenMAID_Global_Tbl_JobVendors_Staging] PRIMARY KEY CLUSTERED ([JobVendorsID] ASC)
);

