CREATE TABLE [TenMAID_Global].[Tbl_MemberPropertyDetails_Staging] (
    [MembershipID]         INT             NOT NULL,
    [MemberID]             INT             NULL,
    [MemberAddressTypeID]  INT             NULL,
    [OwnershipStatus]      INT             NULL,
    [NumberOfBedrooms]     INT             NULL,
    [NumberOfBathrooms]    INT             NULL,
    [Garden]               CHAR (1)        NULL,
    [RegularGardener]      CHAR (1)        NULL,
    [GardenerStartDate]    DATETIME        NULL,
    [GardenerSourcedByTen] BIT             NULL,
    [GardenersVendorID]    INT             NULL,
    [RegularCleaner]       CHAR (1)        NULL,
    [CleanerStartDate]     DATETIME        NULL,
    [CleanerSourcedByTen]  BIT             NULL,
    [CleanersVendorID]     INT             NULL,
    [Nanny]                CHAR (1)        NULL,
    [AccessParking]        NVARCHAR (2000) NULL,
    [DateCreated]          DATETIME        NULL,
    [DateUpdated]          DATETIME        NULL,
    [CreatedBy]            INT             NULL,
    [UpdatedBy]            INT             NULL,
    [TypeOfProperty]       INT             NULL,
    [PropertyAgeStatus]    INT             NULL,
    [OtherTypeOfProperty]  VARCHAR (100)   NULL,
    [SYS_CHANGE_OPERATION] NVARCHAR (1)    NULL,
    [SYS_CHANGE_VERSION]   BIGINT          NULL,
    CONSTRAINT [PK_Tbl_MemberPropertyDetails_Staging] PRIMARY KEY CLUSTERED ([MembershipID] ASC)
);

