CREATE TABLE [TenMAID_Global].[Tbl_ML_RewardsCaluationByJobs_Staging] (
    [Airline]                     NVARCHAR (50) NULL,
    [AvailablePoints]             FLOAT (53)    NULL,
    [BaseAward]                   NVARCHAR (30) NULL,
    [BaseAwardAgain]              NVARCHAR (30) NULL,
    [BaseAwardAvailablePoints]    NVARCHAR (30) NULL,
    [ClassID]                     INT           NULL,
    [datecreated]                 DATETIME      NULL,
    [DateOfRequest]               DATETIME      NULL,
    [dateupdated]                 DATETIME      NULL,
    [DestinationAirportCode]      NVARCHAR (3)  NULL,
    [DestinationID]               INT           NULL,
    [Eligibility]                 NVARCHAR (30) NULL,
    [EliteRewardRedemptionID]     INT           NULL,
    [ID]                          INT           NOT NULL,
    [JobID]                       INT           NULL,
    [MDV]                         NVARCHAR (30) NULL,
    [MemberID]                    INT           NULL,
    [OriginAirportCode]           NVARCHAR (3)  NULL,
    [OutOfPocketCost]             NVARCHAR (50) NULL,
    [OutOfPocketCostWithCCcharge] NVARCHAR (50) NULL,
    [PerTicketCost]               FLOAT (53)    NULL,
    [QualifyingTickets]           FLOAT (53)    NULL,
    [RemainingPoints]             NVARCHAR (30) NULL,
    [RewardBookingStatus]         INT           NULL,
    [Scenarios]                   NVARCHAR (30) NULL,
    [TicketPriceMDV]              NVARCHAR (30) NULL,
    [TicketsRequested]            FLOAT (53)    NULL,
    [TicketTrigger]               FLOAT (53)    NULL,
    [TotalPointsRequired]         NVARCHAR (30) NULL,
    [TotalRequestedwithPoints]    FLOAT (53)    NULL,
    [TotalTicketCost]             FLOAT (53)    NULL,
    [SYS_CHANGE_OPERATION]        NVARCHAR (1)  NULL,
    [SYS_CHANGE_VERSION]          BIGINT        NULL,
    [ForeignID]                   INT           NULL,
    CONSTRAINT [PK_TenMAID_Global_Tbl_ML_RewardsCaluationByJobs_Staging] PRIMARY KEY CLUSTERED ([ID] ASC)
);

