CREATE TABLE [TenMAID_Global].[Tbl_Vendors] (
    [Address]                    NVARCHAR (200)  NULL,
    [AppCategoryTypeID]          INT             NULL,
    [Commission]                 FLOAT (53)      NULL,
    [CommissionAgreed]           BIT             NULL,
    [CommissionOther]            NVARCHAR (200)  NULL,
    [ComplexCommission]          BIT             NULL,
    [ContractedEntity]           INT             NULL,
    [ContractingTerm]            DATETIME        NULL,
    [Country]                    VARCHAR (4)     NULL,
    [CreatedBy]                  INT             NULL,
    [Currency]                   INT             NULL,
    [DateCommissioned]           DATETIME        NULL,
    [DateCreated]                DATETIME        NULL,
    [DateDueDiligenceCompleted]  DATETIME        NULL,
    [DateParterned]              DATETIME        NULL,
    [DateUpdated]                DATETIME        NULL,
    [DomesticBuyVAT]             VARCHAR (100)   NULL,
    [DomesticCommissionVAT]      VARCHAR (100)   NULL,
    [DomesticSellVAT]            VARCHAR (100)   NULL,
    [EUBuyVAT]                   VARCHAR (100)   NULL,
    [EUCommissionVAT]            VARCHAR (100)   NULL,
    [EUSellVAT]                  VARCHAR (100)   NULL,
    [ExternalRating]             INT             NULL,
    [GeneralContactEmail]        NVARCHAR (100)  NULL,
    [GeneralContactPhone]        NVARCHAR (50)   NULL,
    [HaveCommission]             BIT             NULL,
    [InternationalBuyVAT]        VARCHAR (100)   NULL,
    [InternationalCommissionVAT] VARCHAR (100)   NULL,
    [InternationalSellVAT]       VARCHAR (100)   NULL,
    [InvoiceMode]                INT             NULL,
    [InvoicingPeriod]            INT             NULL,
    [Is24H]                      BIT             NULL,
    [IsActive]                   BIT             NULL,
    [isDueDiligenceCompleted]    BIT             NULL,
    [IsMultipleInvoice]          BIT             NULL,
    [IsPartnered]                BIT             NULL,
    [LegalEntityName]            NVARCHAR (500)  NULL,
    [LinkedJob]                  INT             NULL,
    [Name]                       NVARCHAR (200)  NOT NULL,
    [NextReviewDate]             DATETIME        NULL,
    [PaymentProcID]              INT             NULL,
    [ProposedByID]               INT             NULL,
    [ReadyForApp]                BIT             NULL,
    [TenContactEmail]            NVARCHAR (255)  NULL,
    [TenContactName]             NVARCHAR (200)  NULL,
    [TenContactPhone]            NVARCHAR (200)  NULL,
    [TenContactPosition]         NVARCHAR (200)  NULL,
    [UpdatedBy]                  INT             NULL,
    [VATNumber]                  VARCHAR (150)   NULL,
    [VendorID]                   INT             NOT NULL,
    [VendorStatusID]             INT             NULL,
    [WebSiteAddress]             NVARCHAR (1000) NULL,
    CONSTRAINT [PK_TenMAID_Global_Tbl_Vendors] PRIMARY KEY CLUSTERED ([VendorID] ASC)
);

