CREATE TABLE [ivector].[BookingData_Flight] (
    [Booking Status]              VARCHAR (50)    NULL,
    [Booking Reference]           VARCHAR (50)    NULL,
    [Booking Type]                VARCHAR (50)    NULL,
    [Component Name]              VARCHAR (255)   NULL,
    [Component Type]              VARCHAR (50)    NULL,
    [Customer External Reference] VARCHAR (50)    NULL,
    [External Reference]          VARCHAR (50)    NULL,
    [Lead Guest First Name]       VARCHAR (50)    NULL,
    [Lead Guest Last Name]        VARCHAR (50)    NULL,
    [Lead Guest Title]            VARCHAR (50)    NULL,
    [Arrival Airport]             VARCHAR (255)   NULL,
    [Arrival Airport Code]        VARCHAR (50)    NULL,
    [Arrival Date]                DATETIME        NULL,
    [Date Added Date]             DATETIME        NULL,
    [Departure Airport]           VARCHAR (255)   NULL,
    [Departure Airport Code]      VARCHAR (50)    NULL,
    [Departure Date]              DATETIME        NULL,
    [Payment Due Date]            DATETIME        NULL,
    [Return Date]                 DATETIME        NULL,
    [Supplier]                    VARCHAR (50)    NULL,
    [System User]                 VARCHAR (50)    NULL,
    [System User Email]           VARCHAR (50)    NULL,
    [System User Reference]       VARCHAR (50)    NULL,
    [ABTAATOLNumber]              VARCHAR (50)    NULL,
    [Trade]                       VARCHAR (255)   NULL,
    [Brand]                       VARCHAR (255)   NULL,
    [Component Booking Status]    VARCHAR (50)    NULL,
    [Currency]                    VARCHAR (50)    NULL,
    [Currency Code]               VARCHAR (50)    NULL,
    [Selling Currency]            VARCHAR (50)    NULL,
    [Selling Currency Symbol]     VARCHAR (50)    NULL,
    [Sales Channel]               VARCHAR (50)    NULL,
    [Booking Cancelled Date]      DATETIME        NULL,
    [Component Cancelled Date]    DATETIME        NULL,
    [Booking Date]                DATETIME        NULL,
    [Pay With Customer Card]      VARCHAR (50)    NULL,
    [Component Reference]         VARCHAR (50)    NULL,
    [Customer Cost]               VARCHAR (50)    NULL,
    [Customer Total]              VARCHAR (50)    NULL,
    [Duration]                    BIGINT          NULL,
    [Local Cost]                  VARCHAR (50)    NULL,
    [Total Cost]                  VARCHAR (50)    NULL,
    [Total Passengers]            BIGINT          NULL,
    [Total Price]                 VARCHAR (50)    NULL,
    [Customer Total Price]        VARCHAR (50)    NULL,
    [Local Buying Commission]     VARCHAR (50)    NULL,
    [FileName]                    NVARCHAR (1000) NULL
);

