CREATE TABLE [ivector].[BookingData_FCA] (
    [BookingData_FCAID]        INT            IDENTITY (1, 1) NOT NULL,
    [Booking_Reference]        INT            NULL,
    [Component_Type]           NVARCHAR (100) NULL,
    [Brand]                    NVARCHAR (100) NULL,
    [Component_Booking_Status] NVARCHAR (100) NULL,
    [Finance_Audit_Category]   NVARCHAR (100) NULL,
    [Owner_System_User]        NVARCHAR (100) NULL,
    [Booking_Date]             DATETIME2 (7)  NULL,
    [Change_Time_Date]         DATETIME2 (7)  NULL,
    [Currency]                 NVARCHAR (100) NULL,
    [Currency_Code]            NVARCHAR (100) NULL,
    [Selling_Currency]         NVARCHAR (100) NULL,
    [Selling_Currency_Code]    NVARCHAR (100) NULL,
    [Our_Reference]            NVARCHAR (100) NULL,
    [Supplier]                 NVARCHAR (100) NULL,
    [Supplier_Reference]       NVARCHAR (100) NULL,
    [System_User]              NVARCHAR (100) NULL,
    [Commission]               FLOAT (53)     NULL,
    [Commission_Change]        FLOAT (53)     NULL,
    [Current_Margin]           FLOAT (53)     NULL,
    [Local_Cost]               FLOAT (53)     NULL,
    [Local_Cost_Change]        FLOAT (53)     NULL,
    [Margin_Change]            FLOAT (53)     NULL,
    [Original_Commission]      FLOAT (53)     NULL,
    [Original_Local_Cost]      FLOAT (53)     NULL,
    [Original_Margin]          FLOAT (53)     NULL,
    [Original_Selling_Price]   FLOAT (53)     NULL,
    [Original_System_Cost]     FLOAT (53)     NULL,
    [Original_System_Price]    FLOAT (53)     NULL,
    [Selling_Price]            FLOAT (53)     NULL,
    [Selling_Price_Change]     FLOAT (53)     NULL,
    [System_Cost]              FLOAT (53)     NULL,
    [System_Cost_Change]       FLOAT (53)     NULL,
    [System_Price]             FLOAT (53)     NULL,
    [System_Price_Change]      FLOAT (53)     NULL,
    [InsertedOn]               DATETIME2 (7)  NULL,
    [FileName]                 NVARCHAR (200) NULL,
    [Component_Reference]      NVARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([BookingData_FCAID] ASC)
);

