CREATE TABLE [ivector].[BookingData_All_Refunds_Receipts] (
    [BookingData_All_Refunds_ReceiptsID] INT             IDENTITY (1, 1) NOT NULL,
    [Booking_Reference]                  INT             NULL,
    [Bank_Transfer_Reference]            NVARCHAR (100)  NULL,
    [Job_ID]                             NVARCHAR (100)  NULL,
    [CCTransaction_Id]                   NVARCHAR (1000) NULL,
    [Credit_Card_Holder_Name]            NVARCHAR (100)  NULL,
    [Credit_Card_Number]                 NVARCHAR (100)  NULL,
    [Credit_Card_Type]                   NVARCHAR (100)  NULL,
    [Custom_Payment_Reference]           NVARCHAR (1000) NULL,
    [Member_ID]                          NVARCHAR (100)  NULL,
    [Lead_Guest_First_Name]              NVARCHAR (100)  NULL,
    [Lead_Guest_Last_Name]               NVARCHAR (100)  NULL,
    [Payment_Detail]                     NVARCHAR (100)  NULL,
    [Trade_Reference]                    NVARCHAR (100)  NULL,
    [Booking_Status]                     NVARCHAR (100)  NULL,
    [CCPayment_Provider]                 NVARCHAR (100)  NULL,
    [Custom_Payment_Type]                NVARCHAR (1000) NULL,
    [Sales_Channel]                      NVARCHAR (100)  NULL,
    [System_User]                        NVARCHAR (100)  NULL,
    [System_User_Reference]              NVARCHAR (100)  NULL,
    [Trade_Group]                        NVARCHAR (100)  NULL,
    [Booking_Date]                       DATETIME2 (7)   NULL,
    [Departure_Date]                     DATETIME2 (7)   NULL,
    [Payment_Date]                       DATETIME2 (7)   NULL,
    [Currency_Code]                      NVARCHAR (100)  NULL,
    [Brand]                              NVARCHAR (100)  NULL,
    [Corporate_Scheme_ID]                NVARCHAR (100)  NULL,
    [Balance]                            VARCHAR (100)   NULL,
    [Outstanding]                        VARCHAR (100)   NULL,
    [Payment_Amount]                     VARCHAR (100)   NULL,
    [Payment_Total_Payment]              VARCHAR (100)   NULL,
    [Total]                              VARCHAR (100)   NULL,
    [Total_Payment]                      VARCHAR (100)   NULL,
    [InsertOn]                           DATETIME        NULL,
    [FileName]                           NVARCHAR (200)  NULL
);

