CREATE TABLE [ivector].[BookingData_All_Refunds_Receipts_v4] (
    [BookingData_All_Refunds_Receipts_v4ID] INT             IDENTITY (1, 1) NOT NULL,
    [Booking Reference]                     BIGINT          NULL,
    [Lead Guest First Name]                 NVARCHAR (100)  NULL,
    [Lead Guest Last Name]                  NVARCHAR (100)  NULL,
    [Booking Date]                          DATETIME        NULL,
    [Departure Date]                        DATETIME        NULL,
    [System User]                           NVARCHAR (100)  NULL,
    [System User Reference]                 NVARCHAR (100)  NULL,
    [Brand]                                 NVARCHAR (100)  NULL,
    [Booking Status]                        NVARCHAR (100)  NULL,
    [Currency Code]                         NVARCHAR (100)  NULL,
    [Sales Channel]                         NVARCHAR (100)  NULL,
    [Bank Transfer Reference]               NVARCHAR (100)  NULL,
    [Job ID]                                NVARCHAR (100)  NULL,
    [CCTransaction Id]                      NVARCHAR (1000) NULL,
    [Credit Card Holder Name]               NVARCHAR (100)  NULL,
    [Credit Card Number]                    NVARCHAR (100)  NULL,
    [Credit Card Type]                      NVARCHAR (100)  NULL,
    [Custom Payment Reference]              NVARCHAR (1000) NULL,
    [Member ID]                             NVARCHAR (100)  NULL,
    [Payment Detail]                        NVARCHAR (100)  NULL,
    [Trade Reference]                       NVARCHAR (100)  NULL,
    [CCPayment Provider]                    NVARCHAR (100)  NULL,
    [Custom Payment Type]                   NVARCHAR (100)  NULL,
    [Trade Group]                           NVARCHAR (100)  NULL,
    [Payment Date]                          DATETIME        NULL,
    [Corporate Scheme ID]                   NVARCHAR (100)  NULL,
    [Balance]                               VARCHAR (100)   NULL,
    [Outstanding]                           VARCHAR (100)   NULL,
    [Payment Amount]                        VARCHAR (100)   NULL,
    [Payment Total Payment]                 VARCHAR (100)   NULL,
    [Total]                                 VARCHAR (100)   NULL,
    [Total Payment]                         VARCHAR (100)   NULL,
    [InsertedOn]                            DATETIME        NULL,
    [FileName]                              NVARCHAR (129)  NULL
);

