CREATE TABLE [ivector].[BookingData_CarHire] (
    [Booking Reference]           VARCHAR (50)    NULL,
    [Component Reference]         VARCHAR (50)    NULL,
    [Component Type]              VARCHAR (50)    NULL,
    [Customer External Reference] VARCHAR (50)    NULL,
    [External Reference]          VARCHAR (50)    NULL,
    [Lead Guest Email]            VARCHAR (50)    NULL,
    [Lead Guest First Name]       VARCHAR (50)    NULL,
    [Lead Guest Last Name]        VARCHAR (50)    NULL,
    [Lead Guest Title]            VARCHAR (50)    NULL,
    [Source Reference]            VARCHAR (1000)  NULL,
    [Car Hire Drop Off Depot]     VARCHAR (255)   NULL,
    [Car Hire Pick Up Depot]      VARCHAR (255)   NULL,
    [Pay Local]                   VARCHAR (50)    NULL,
    [Arrival Date]                DATETIME        NULL,
    [Booking Date]                DATETIME        NULL,
    [Departure Date]              DATETIME        NULL,
    [Supplier]                    VARCHAR (50)    NULL,
    [System User]                 VARCHAR (50)    NULL,
    [System User Email]           VARCHAR (50)    NULL,
    [System User Reference]       VARCHAR (50)    NULL,
    [ABTAATOLNumber]              VARCHAR (50)    NULL,
    [Trade]                       VARCHAR (255)   NULL,
    [Brand]                       VARCHAR (50)    NULL,
    [Booking Status]              VARCHAR (50)    NULL,
    [Component Booking Status]    VARCHAR (50)    NULL,
    [Currency]                    VARCHAR (50)    NULL,
    [Currency Code]               VARCHAR (50)    NULL,
    [Selling Currency]            VARCHAR (50)    NULL,
    [Selling Currency Symbol]     VARCHAR (50)    NULL,
    [Component Name]              VARCHAR (255)   NULL,
    [Sales Channel]               VARCHAR (50)    NULL,
    [Customer Cost]               VARCHAR (50)    NULL,
    [Customer Total]              VARCHAR (50)    NULL,
    [Customer Total Price]        VARCHAR (50)    NULL,
    [Duration]                    VARCHAR (50)    NULL,
    [Local Cost]                  VARCHAR (50)    NULL,
    [Total Commission]            VARCHAR (50)    NULL,
    [Total Cost]                  VARCHAR (50)    NULL,
    [Total Passengers]            VARCHAR (50)    NULL,
    [Local Buying Commission]     VARCHAR (50)    NULL,
    [InsertedOn]                  DATETIME        NULL,
    [FileName]                    NVARCHAR (1000) NULL
);

