CREATE TABLE [ivector].[BookingData_All] (
    [BookingData_AllID]               INT            IDENTITY (1, 1) NOT NULL,
    [Booking_Status]                  NVARCHAR (100) NOT NULL,
    [Booking_Reference]               INT            NULL,
    [Booking_Type]                    NVARCHAR (100) NULL,
    [Component_Name]                  NVARCHAR (200) NULL,
    [Component_Type]                  NVARCHAR (100) NULL,
    [Customer_External_Reference]     NVARCHAR (100) NULL,
    [External_Reference]              NVARCHAR (100) NULL,
    [Lead_Guest_First_Name]           NVARCHAR (100) NULL,
    [Lead_Guest_Last_Name]            NVARCHAR (100) NULL,
    [Lead_Guest_Title]                NVARCHAR (100) NULL,
    [Arrival_Airport]                 NVARCHAR (200) NULL,
    [Arrival_Airport_Code]            NVARCHAR (100) NULL,
    [Arrival_Date]                    DATETIME2 (7)  NULL,
    [Date_Added_Date]                 DATETIME2 (7)  NULL,
    [Departure_Airport]               NVARCHAR (200) NULL,
    [Departure_Airport_Code]          NVARCHAR (100) NULL,
    [Departure_Date]                  DATETIME2 (7)  NULL,
    [Payment_Due_Date]                DATETIME2 (7)  NULL,
    [Return_Date]                     DATETIME2 (7)  NULL,
    [Supplier]                        NVARCHAR (100) NULL,
    [System_User]                     NVARCHAR (100) NULL,
    [System_User_Email]               NVARCHAR (100) NULL,
    [System_User_Reference]           NVARCHAR (100) NULL,
    [ABTAATOLNumber]                  NVARCHAR (100) NULL,
    [Trade]                           NVARCHAR (100) NULL,
    [Brand]                           NVARCHAR (100) NULL,
    [Component_Booking_Status]        NVARCHAR (100) NULL,
    [Sales_Channel]                   NVARCHAR (100) NULL,
    [Currency]                        NVARCHAR (100) NULL,
    [Currency_Code]                   NVARCHAR (100) NULL,
    [Selling_Currency]                NVARCHAR (100) NULL,
    [Selling_Currency_Symbol]         NVARCHAR (100) NULL,
    [Booking_Cancelled_Date]          DATETIME2 (7)  NULL,
    [Component_Cancelled_Date]        DATETIME2 (7)  NULL,
    [Booking_Date]                    DATETIME2 (7)  NULL,
    [Pay_With_Customer_Card]          BIT            NULL,
    [Component_Reference]             NVARCHAR (255) NULL,
    [Booking_Component]               NVARCHAR (100) NULL,
    [Geography_Level_1]               NVARCHAR (200) NULL,
    [Geography_Level_2]               NVARCHAR (200) NULL,
    [Geography_Level_3]               NVARCHAR (200) NULL,
    [Car_Hire_Drop_Off_Depot]         NVARCHAR (200) NULL,
    [Car_Hire_Pick_Up_Depot]          NVARCHAR (200) NULL,
    [Source_Reference]                NVARCHAR (200) NULL,
    [Source_Reference_Split]          NVARCHAR (200) NULL,
    [Supplier_Confirmation_Reference] NVARCHAR (200) NULL,
    [Last_Modified_Date]              NVARCHAR (200) NULL,
    [Pay_Local]                       BIT            NULL,
    [Customer_Cost]                   FLOAT (53)     NULL,
    [Customer_Total]                  FLOAT (53)     NULL,
    [Duration]                        NVARCHAR (100) NULL,
    [Local_Cost]                      FLOAT (53)     NULL,
    [Total_Cost]                      FLOAT (53)     NULL,
    [Customer_Total_Price]            FLOAT (53)     NULL,
    [Local_Buying_Commission]         FLOAT (53)     NULL,
    [Total_Passengers]                NVARCHAR (100) NULL,
    [Total_Price]                     FLOAT (53)     NULL,
    [InsertedOn]                      DATETIME2 (7)  NULL,
    [FileName]                        NVARCHAR (200) NULL,
    [Buying_Commission]               FLOAT (53)     NULL,
    PRIMARY KEY CLUSTERED ([BookingData_AllID] ASC)
);

