CREATE TABLE [ivector].[BookingData_Extra] (
    [Booking Reference]           VARCHAR (50)    NULL,
    [Booking Type]                VARCHAR (50)    NULL,
    [Component Name]              VARCHAR (1000)  NULL,
    [Component Reference]         VARCHAR (1000)  NULL,
    [Customer External Reference] VARCHAR (50)    NULL,
    [External Reference]          VARCHAR (50)    NULL,
    [Lead Guest Email]            VARCHAR (50)    NULL,
    [Lead Guest First Name]       VARCHAR (50)    NULL,
    [Lead Guest Last Name]        VARCHAR (50)    NULL,
    [Lead Guest Title]            VARCHAR (50)    NULL,
    [Source Reference]            VARCHAR (1000)  NULL,
    [Arrival Date]                DATE            NULL,
    [Booking Date]                DATE            NULL,
    [Departure Date]              DATE            NULL,
    [Geo Id Level 1]              INT             NULL,
    [Geography Level 1]           VARCHAR (50)    NULL,
    [Geo Id Level 2]              INT             NULL,
    [Geography Level 2]           VARCHAR (50)    NULL,
    [Geo Id Level 3]              INT             NULL,
    [Geography Level 3]           VARCHAR (50)    NULL,
    [Supplier]                    VARCHAR (50)    NULL,
    [ABTAATOLNumber]              VARCHAR (50)    NULL,
    [Trade]                       VARCHAR (1000)  NULL,
    [Booking Status]              VARCHAR (50)    NULL,
    [Component Booking Status]    VARCHAR (50)    NULL,
    [Brand]                       VARCHAR (50)    NULL,
    [Currency]                    VARCHAR (50)    NULL,
    [Currency Code]               VARCHAR (50)    NULL,
    [Selling Currency]            VARCHAR (50)    NULL,
    [Selling Currency Symbol]     VARCHAR (50)    NULL,
    [Sales Channel]               VARCHAR (50)    NULL,
    [Component Type]              VARCHAR (50)    NULL,
    [Customer Cost]               FLOAT (53)      NULL,
    [Customer Total]              FLOAT (53)      NULL,
    [Customer Total Price]        FLOAT (53)      NULL,
    [Duration]                    INT             NULL,
    [Total Commission]            VARCHAR (50)    NULL,
    [Total Cost]                  FLOAT (53)      NULL,
    [Total Passengers]            INT             NULL,
    [Total Price]                 FLOAT (53)      NULL,
    [Local Buying Commission]     FLOAT (53)      NULL,
    [InsertedOn]                  DATETIME        NULL,
    [FileName]                    NVARCHAR (1000) NULL
);

