CREATE TABLE [ivector].[BookingData_Property] (
    [Booking Status]              VARCHAR (100)  NULL,
    [Booking Reference]           VARCHAR (100)  NULL,
    [Booking Type]                VARCHAR (100)  NULL,
    [Component Name]              VARCHAR (1000) NULL,
    [Component Type]              VARCHAR (100)  NULL,
    [Customer External Reference] VARCHAR (100)  NULL,
    [External Reference]          VARCHAR (100)  NULL,
    [Lead Guest First Name]       VARCHAR (100)  NULL,
    [Lead Guest Last Name]        VARCHAR (100)  NULL,
    [Lead Guest Title]            VARCHAR (100)  NULL,
    [Arrival Airport]             VARCHAR (100)  NULL,
    [Arrival Airport Code]        VARCHAR (100)  NULL,
    [Arrival Date]                VARCHAR (100)  NULL,
    [Date Added Date]             VARCHAR (100)  NULL,
    [Departure Airport]           VARCHAR (100)  NULL,
    [Departure Airport Code]      VARCHAR (100)  NULL,
    [Departure Date]              VARCHAR (100)  NULL,
    [Payment Due Date]            VARCHAR (100)  NULL,
    [Return Date]                 VARCHAR (100)  NULL,
    [Supplier]                    VARCHAR (100)  NULL,
    [System User]                 VARCHAR (100)  NULL,
    [System User Email]           VARCHAR (100)  NULL,
    [System User Reference]       VARCHAR (100)  NULL,
    [ABTAATOLNumber]              VARCHAR (100)  NULL,
    [Trade]                       VARCHAR (1000) NULL,
    [Brand]                       VARCHAR (100)  NULL,
    [Component Booking Status]    VARCHAR (100)  NULL,
    [Sales Channel]               VARCHAR (100)  NULL,
    [Currency]                    VARCHAR (100)  NULL,
    [Currency Code]               VARCHAR (100)  NULL,
    [Selling Currency]            VARCHAR (100)  NULL,
    [Selling Currency Symbol]     VARCHAR (100)  NULL,
    [Booking Cancelled Date]      VARCHAR (100)  NULL,
    [Component Cancelled Date]    VARCHAR (100)  NULL,
    [Booking Date]                VARCHAR (100)  NULL,
    [Pay With Customer Card]      VARCHAR (100)  NULL,
    [Component Reference]         VARCHAR (100)  NULL,
    [Customer Cost]               VARCHAR (100)  NULL,
    [Customer Total]              VARCHAR (100)  NULL,
    [Duration]                    VARCHAR (100)  NULL,
    [Local Cost]                  VARCHAR (100)  NULL,
    [Total Cost]                  VARCHAR (100)  NULL,
    [Customer Total Price]        VARCHAR (100)  NULL,
    [Local Buying Commission]     VARCHAR (100)  NULL,
    [Total Passengers]            VARCHAR (100)  NULL,
    [Total Price]                 VARCHAR (100)  NULL,
    [InsertedOn]                  DATETIME       NULL,
    [FileName]                    NVARCHAR (100) NULL
);

