CREATE TABLE [ivector].[FlightBookingTicketReport] (
    [FlightBookingTicketID]  INT             NULL,
    [DateAdded]              DATETIME2 (7)   NULL,
    [LastModifiedDate]       DATETIME2 (7)   NULL,
    [IssueDate]              DATE            NULL,
    [BSPIssueDate]           DATE            NULL,
    [BSPIssueDate1]          DATE            NULL,
    [PayLocal]               BIT             NULL,
    [PayWithCustomerCard]    BIT             NULL,
    [CreditCardPaymentType]  NVARCHAR (200)  NULL,
    [BookingReference]       NVARCHAR (200)  NULL,
    [FlightBookingReference] NVARCHAR (200)  NULL,
    [TicketNumber]           NVARCHAR (200)  NULL,
    [Type]                   NVARCHAR (200)  NULL,
    [FirstName]              NVARCHAR (200)  NULL,
    [LastName]               NVARCHAR (200)  NULL,
    [PassengerType]          NVARCHAR (50)   NULL,
    [Column1]                NVARCHAR (200)  NULL,
    [BookingClass]           NVARCHAR (200)  NULL,
    [Airport]                NVARCHAR (200)  NULL,
    [Airport1]               NVARCHAR (200)  NULL,
    [GrossFare]              FLOAT (53)      NULL,
    [Tax]                    FLOAT (53)      NULL,
    [AmountPayable]          FLOAT (53)      NULL,
    [BSPGrossFare]           FLOAT (53)      NULL,
    [BSPTax]                 FLOAT (53)      NULL,
    [BSPAmountPayable]       FLOAT (53)      NULL,
    [BrandName]              NVARCHAR (200)  NULL,
    [TradeName]              NVARCHAR (200)  NULL,
    [JobNumber]              NVARCHAR (200)  NULL,
    [MemberId]               NVARCHAR (200)  NULL,
    [FlightCarrier]          NVARCHAR (200)  NULL,
    [FileName]               NVARCHAR (1000) NULL
);

