CREATE TABLE [ivector].[NEW2BookingData_All] (
    [Booking Status]                  NVARCHAR (100)  NULL,
    [Booking Reference]               INT             NULL,
    [Booking Type]                    NVARCHAR (100)  NULL,
    [Component Name]                  NVARCHAR (200)  NULL,
    [Component Type]                  NVARCHAR (100)  NULL,
    [Customer External Reference]     NVARCHAR (100)  NULL,
    [External Reference]              NVARCHAR (1000) NULL,
    [Lead Guest First Name]           NVARCHAR (100)  NULL,
    [Lead Guest Last Name]            NVARCHAR (100)  NULL,
    [Lead Guest Title]                NVARCHAR (100)  NULL,
    [Arrival Airport]                 NVARCHAR (200)  NULL,
    [Arrival Airport Code]            NVARCHAR (100)  NULL,
    [Arrival Date]                    DATETIME2 (7)   NULL,
    [Date Added Date]                 DATETIME2 (7)   NULL,
    [Departure Airport]               NVARCHAR (200)  NULL,
    [Departure Airport Code]          NVARCHAR (100)  NULL,
    [Departure Date]                  DATETIME2 (7)   NULL,
    [Payment Due Date]                DATETIME2 (7)   NULL,
    [Return Date]                     DATETIME2 (7)   NULL,
    [Supplier]                        NVARCHAR (100)  NULL,
    [System User]                     NVARCHAR (100)  NULL,
    [System User Email]               NVARCHAR (100)  NULL,
    [System User Reference]           NVARCHAR (100)  NULL,
    [ABTAATOLNumber]                  NVARCHAR (100)  NULL,
    [Trade]                           NVARCHAR (100)  NULL,
    [Brand]                           NVARCHAR (100)  NULL,
    [Component Booking Status]        NVARCHAR (100)  NULL,
    [Sales Channel]                   NVARCHAR (100)  NULL,
    [Currency]                        NVARCHAR (100)  NULL,
    [Currency Code]                   NVARCHAR (100)  NULL,
    [Selling Currency]                NVARCHAR (100)  NULL,
    [Selling Currency Symbol]         NVARCHAR (100)  NULL,
    [Booking Cancelled Date]          DATETIME2 (7)   NULL,
    [Component Cancelled Date]        DATETIME2 (7)   NULL,
    [Booking Date]                    DATETIME2 (7)   NULL,
    [Pay With Customer Card]          BIT             NULL,
    [Component Reference]             NVARCHAR (1000) NULL,
    [Booking Component]               NVARCHAR (100)  NULL,
    [Supplier Confirmation Reference] NVARCHAR (200)  NULL,
    [Source Reference]                NVARCHAR (400)  NULL,
    [Source Reference Split]          NVARCHAR (400)  NULL,
    [Geography Level 1]               NVARCHAR (200)  NULL,
    [Geography Level 2]               NVARCHAR (200)  NULL,
    [Geography Level 3]               NVARCHAR (200)  NULL,
    [TPRate Code]                     NVARCHAR (100)  NULL,
    [Pay Local]                       BIT             NULL,
    [Customer Cost]                   FLOAT (53)      NULL,
    [Customer Total]                  FLOAT (53)      NULL,
    [Duration]                        NVARCHAR (100)  NULL,
    [Local Cost]                      FLOAT (53)      NULL,
    [Total Cost]                      FLOAT (53)      NULL,
    [Customer Total Price]            FLOAT (53)      NULL,
    [Local Buying Commission]         FLOAT (53)      NULL,
    [Total Passengers]                NVARCHAR (100)  NULL,
    [Total Price]                     FLOAT (53)      NULL,
    [Buying Commission]               FLOAT (53)      NULL,
    [InsertedOn]                      DATETIME        NULL,
    [FileName]                        NVARCHAR (1000) NULL
);

