CREATE TABLE [RedShift_visa].[booking_event] (
    [id]                                                      NVARCHAR (512) NULL,
    [received_at]                                             DATETIME2 (7)  NULL,
    [uuid]                                                    BIGINT         NULL,
    [event]                                                   NVARCHAR (512) NULL,
    [uuid_ts]                                                 DATETIME2 (7)  NULL,
    [context_library_version]                                 NVARCHAR (512) NULL,
    [context_page_url]                                        NVARCHAR (512) NULL,
    [context_page_path]                                       NVARCHAR (512) NULL,
    [event_text]                                              NVARCHAR (512) NULL,
    [anonymous_id]                                            NVARCHAR (512) NULL,
    [booking_data_data_hotel_sub_bookings]                    NVARCHAR (512) NULL,
    [user_id]                                                 NVARCHAR (512) NULL,
    [booking_data_data_car_hire_sub_bookings]                 NVARCHAR (512) NULL,
    [booking_data_data_payment_card_valid]                    VARCHAR (5)    NULL,
    [booking_data_data_new_payment_card_details_expiry_month] NVARCHAR (512) NULL,
    [booking_data_data_use_saved_card]                        VARCHAR (5)    NULL,
    [context_library_name]                                    NVARCHAR (512) NULL,
    [timestamp]                                               DATETIME2 (7)  NULL,
    [type]                                                    NVARCHAR (512) NULL,
    [booking_data_data_flight_sub_bookings]                   NVARCHAR (512) NULL,
    [booking_data_data_billing_address]                       NVARCHAR (512) NULL,
    [sent_at]                                                 DATETIME2 (7)  NULL,
    [booking_data_data_new_payment_card_details_cardholder]   NVARCHAR (512) NULL,
    [context_ip]                                              NVARCHAR (512) NULL,
    [original_timestamp]                                      DATETIME2 (7)  NULL,
    [context_page_title]                                      NVARCHAR (512) NULL,
    [booking_data_data_confirmed_terms]                       VARCHAR (5)    NULL,
    [context_user_agent]                                      NVARCHAR (512) NULL,
    [context_page_referrer]                                   NVARCHAR (512) NULL,
    [booking_data_data_preferred_contact_method]              NVARCHAR (512) NULL,
    [booking_data_id]                                         NVARCHAR (512) NULL,
    [booking_data_data_dietary_requirements]                  NVARCHAR (512) NULL,
    [booking_data_data_special_occasion_event]                NVARCHAR (512) NULL,
    [booking_data_data_extra_details]                         NVARCHAR (512) NULL,
    [booking_data_data_delivery_method]                       NVARCHAR (512) NULL,
    [booking_data_data_delivery_address]                      NVARCHAR (512) NULL,
    [booking_data_data_new_payment_card_details_card_type]    NVARCHAR (512) NULL,
    [booking_data_data_new_payment_card_details_expiry_year]  NVARCHAR (512) NULL,
    [booking_data_data_new_payment_card_details_card_number]  NVARCHAR (512) NULL,
    [booking_data_data_new_payment_card_details_cvc]          NVARCHAR (512) NULL,
    [booking_data_data_browser_info_language]                 NVARCHAR (512) NULL,
    [booking_data_data_browser_info_screen_height]            BIGINT         NULL,
    [booking_data_data_browser_info_screen_width]             BIGINT         NULL,
    [booking_data_data_browser_info_java_enabled]             VARCHAR (5)    NULL,
    [booking_data_data_browser_info_timezone_offset]          BIGINT         NULL,
    [booking_data_data_browser_info_color_depth]              BIGINT         NULL,
    [booking_eventId]                                         BIGINT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_RedShift_visa_booking_eventId] PRIMARY KEY CLUSTERED ([booking_eventId] ASC)
);

