CREATE TABLE [RedShift_visa].[booking_request_event] (
    [id]                                                             NVARCHAR (512) NULL,
    [received_at]                                                    DATETIME2 (7)  NULL,
    [uuid]                                                           BIGINT         NULL,
    [type]                                                           NVARCHAR (512) NULL,
    [anonymous_id]                                                   NVARCHAR (512) NULL,
    [context_ip]                                                     NVARCHAR (512) NULL,
    [context_page_title]                                             NVARCHAR (512) NULL,
    [original_timestamp]                                             DATETIME2 (7)  NULL,
    [context_library_name]                                           NVARCHAR (512) NULL,
    [context_library_version]                                        NVARCHAR (512) NULL,
    [request_data_requested_date]                                    DATETIME2 (7)  NULL,
    [request_data_restaurant]                                        NVARCHAR (512) NULL,
    [sent_at]                                                        DATETIME2 (7)  NULL,
    [context_page_path]                                              NVARCHAR (512) NULL,
    [context_page_url]                                               NVARCHAR (512) NULL,
    [event]                                                          NVARCHAR (512) NULL,
    [request_data_preferred_contact_method]                          NVARCHAR (512) NULL,
    [request_data_quantity]                                          BIGINT         NULL,
    [request_data_requested_time]                                    NVARCHAR (512) NULL,
    [timestamp]                                                      DATETIME2 (7)  NULL,
    [uuid_ts]                                                        DATETIME2 (7)  NULL,
    [context_user_agent]                                             NVARCHAR (512) NULL,
    [event_text]                                                     NVARCHAR (512) NULL,
    [request_data_flexible_on_times]                                 VARCHAR (5)    NULL,
    [user_id]                                                        NVARCHAR (512) NULL,
    [request_data_dietary_requirements]                              NVARCHAR (512) NULL,
    [context_page_referrer]                                          NVARCHAR (512) NULL,
    [request_data_extra_details]                                     NVARCHAR (512) NULL,
    [request_data_inbound_location]                                  NVARCHAR (512) NULL,
    [request_data_is_car_hire_briefing]                              VARCHAR (5)    NULL,
    [request_data_inbound_date]                                      DATETIME2 (7)  NULL,
    [request_data_is_hotel_briefing]                                 VARCHAR (5)    NULL,
    [request_data_num_infants]                                       BIGINT         NULL,
    [request_data_outbound_date]                                     DATETIME2 (7)  NULL,
    [request_data_outbound_location]                                 NVARCHAR (512) NULL,
    [request_data_flexible_on_dates]                                 VARCHAR (5)    NULL,
    [request_data_num_adults]                                        BIGINT         NULL,
    [request_data_is_flight_briefing]                                VARCHAR (5)    NULL,
    [request_data_num_children]                                      BIGINT         NULL,
    [request_data_ticket_type]                                       NVARCHAR (512) NULL,
    [request_data_budget]                                            NVARCHAR (512) NULL,
    [request_data_local_hotel_name]                                  NVARCHAR (512) NULL,
    [request_data_passport_name]                                     NVARCHAR (512) NULL,
    [request_data_airport]                                           NVARCHAR (512) NULL,
    [request_data_airport_service_terms_conditions_agreement]        VARCHAR (5)    NULL,
    [request_data_date_of_birth]                                     DATETIME2 (7)  NULL,
    [request_data_flight_direction]                                  NVARCHAR (512) NULL,
    [request_data_flight_number]                                     NVARCHAR (512) NULL,
    [request_data_airport_primary_holder_terms_conditions_agreement] VARCHAR (5)    NULL,
    [request_data_nationality]                                       NVARCHAR (512) NULL,
    [request_data_datetime_of_flight]                                DATETIME2 (7)  NULL,
    [request_data_passport_number]                                   NVARCHAR (512) NULL,
    [request_data_airline]                                           NVARCHAR (512) NULL,
    [request_data_accompanying_guest_passport_name]                  NVARCHAR (512) NULL,
    [request_data_address]                                           BIGINT         NULL,
    [request_data_drop_off_terminal]                                 NVARCHAR (512) NULL,
    [request_data_num_bags]                                          BIGINT         NULL,
    [request_data_pick_up_time]                                      NVARCHAR (512) NULL,
    [request_data_accompanying_guest_passport_number]                NVARCHAR (512) NULL,
    [request_data_flight_date]                                       DATETIME2 (7)  NULL,
    [request_data_accompanying_guest_local_hotel_name]               NVARCHAR (512) NULL,
    [request_data_flight_datetime]                                   DATETIME2 (7)  NULL,
    [request_data_flight_time]                                       NVARCHAR (512) NULL,
    [request_data_pick_up_datetime]                                  DATETIME2 (7)  NULL,
    [request_data_additional_stop]                                   BIGINT         NULL,
    [request_data_accompanying_guest_date_of_birth]                  DATETIME2 (7)  NULL,
    [request_data_num_suitcases]                                     BIGINT         NULL,
    [request_data_accompanying_guest_nationality]                    NVARCHAR (512) NULL,
    [request_data_additional_instructions]                           NVARCHAR (512) NULL,
    [request_data_pick_up_date]                                      DATETIME2 (7)  NULL,
    [request_data_mandatory_contact_phone]                           BIGINT         NULL,
    [request_data_preferred_contact_phone]                           BIGINT         NULL,
    [booking_request_eventId]                                        BIGINT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_RedShift_visa_booking_request_eventId] PRIMARY KEY CLUSTERED ([booking_request_eventId] ASC)
);

