CREATE TABLE [Django].[member_profiles] (
    [user_id]                                 INT                NULL,
    [created]                                 DATETIME2 (0)      NULL,
    [member_id]                               INT                NULL,
    [ten_maid_corporate_scheme_id]            INT                NULL,
    [title]                                   NVARCHAR (4000)    NULL,
    [email]                                   NVARCHAR (4000)    NULL,
    [birth_date]                              DATE               NULL,
    [gender]                                  NVARCHAR (4000)    NULL,
    [country_of_citizenship]                  NVARCHAR (4000)    NULL,
    [preferred_contact_method]                NVARCHAR (4000)    NULL,
    [client_opt_in]                           NVARCHAR (4000)    NULL,
    [ten_opt_in]                              NVARCHAR (4000)    NULL,
    [terms_and_conditions_accepted_timestamp] DATETIMEOFFSET (7) NULL,
    [ten_maid_in_sync]                        NVARCHAR (4000)    NULL,
    [password_email_sent_datetime]            DATETIMEOFFSET (7) NULL,
    [enable_calendar_invites]                 NVARCHAR (4000)    NULL,
    [enable_booking_reminders]                NVARCHAR (4000)    NULL,
    [login_from_new_device_emails]            NVARCHAR (4000)    NULL,
    [two_step_login]                          NVARCHAR (4000)    NULL,
    [weekly_newsletter]                       NVARCHAR (4000)    NULL,
    [member_events_invite]                    NVARCHAR (4000)    NULL,
    [dining_interest]                         NVARCHAR (4000)    NULL,
    [music_tickets]                           NVARCHAR (4000)    NULL,
    [theatre_interest]                        NVARCHAR (4000)    NULL,
    [art_exhibitions]                         NVARCHAR (4000)    NULL,
    [events_for_children]                     NVARCHAR (4000)    NULL,
    [other_attractions]                       NVARCHAR (4000)    NULL,
    [accessory_events_clothing]               NVARCHAR (4000)    NULL,
    [travel_inspiration]                      NVARCHAR (4000)    NULL,
    [hotel_openings]                          NVARCHAR (4000)    NULL,
    [flight_sales]                            NVARCHAR (4000)    NULL,
    [viewed_tour]                             NVARCHAR (4000)    NULL,
    [account_activated]                       NVARCHAR (4000)    NULL,
    [password_hash]                           NVARCHAR (4000)    NULL,
    [inserted_on]                             DATETIME           NOT NULL,
    [processid]                               VARCHAR (255)      NULL
);

