CREATE TABLE [RedShift_scotia_pursuits].[search] (
    [id]                                 NVARCHAR (512) NULL,
    [received_at]                        DATETIME2 (7)  NULL,
    [uuid]                               BIGINT         NULL,
    [query_end_date]                     DATETIME2 (7)  NULL,
    [query_num_children]                 BIGINT         NULL,
    [context_library_version]            NVARCHAR (512) NULL,
    [context_page_title]                 NVARCHAR (512) NULL,
    [module]                             NVARCHAR (512) NULL,
    [query_num_infants]                  BIGINT         NULL,
    [timestamp]                          DATETIME2 (7)  NULL,
    [context_library_name]               NVARCHAR (512) NULL,
    [context_page_path]                  NVARCHAR (512) NULL,
    [original_timestamp]                 DATETIME2 (7)  NULL,
    [query_end_date_full]                DATETIME2 (7)  NULL,
    [query_start_date]                   DATETIME2 (7)  NULL,
    [user_id]                            NVARCHAR (512) NULL,
    [anonymous_id]                       NVARCHAR (512) NULL,
    [query_children]                     NVARCHAR (512) NULL,
    [query_end_location]                 NVARCHAR (512) NULL,
    [query_flight_class]                 NVARCHAR (512) NULL,
    [query_start_location]               NVARCHAR (512) NULL,
    [context_page_url]                   NVARCHAR (512) NULL,
    [query_room_requests]                NVARCHAR (512) NULL,
    [sub_module]                         NVARCHAR (512) NULL,
    [event]                              NVARCHAR (512) NULL,
    [query_driver_age]                   NVARCHAR (512) NULL,
    [query_num_adults]                   BIGINT         NULL,
    [query_start_time]                   NVARCHAR (512) NULL,
    [uuid_ts]                            DATETIME2 (7)  NULL,
    [context_ip]                         NVARCHAR (512) NULL,
    [query_end_time]                     NVARCHAR (512) NULL,
    [context_user_agent]                 NVARCHAR (512) NULL,
    [event_text]                         NVARCHAR (512) NULL,
    [query_start_date_full]              DATETIME2 (7)  NULL,
    [sent_at]                            DATETIME2 (7)  NULL,
    [query]                              NVARCHAR (512) NULL,
    [query_airline]                      NVARCHAR (512) NULL,
    [context_page_referrer]              NVARCHAR (512) NULL,
    [context_page_search]                NVARCHAR (512) NULL,
    [query_selected_start_location_name] NVARCHAR (512) NULL,
    [query_object_type]                  NVARCHAR (512) NULL,
    [query_selected_end_location_name]   NVARCHAR (512) NULL,
    [searchId]                           BIGINT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_RedShift_scotia_pursuits_searchId] PRIMARY KEY CLUSTERED ([searchId] ASC)
);

