CREATE TABLE [RedShift_scotia_pursuits].[submit_request] (
    [id]                      NVARCHAR (512) NULL,
    [received_at]             DATETIME2 (7)  NULL,
    [uuid]                    BIGINT         NULL,
    [context_library_name]    NVARCHAR (512) NULL,
    [context_page_title]      NVARCHAR (512) NULL,
    [context_page_url]        NVARCHAR (512) NULL,
    [context_user_agent]      NVARCHAR (512) NULL,
    [request_type]            NVARCHAR (512) NULL,
    [uuid_ts]                 DATETIME2 (7)  NULL,
    [anonymous_id]            NVARCHAR (512) NULL,
    [event]                   NVARCHAR (512) NULL,
    [user_id]                 NVARCHAR (512) NULL,
    [context_ip]              NVARCHAR (512) NULL,
    [context_library_version] NVARCHAR (512) NULL,
    [context_page_path]       NVARCHAR (512) NULL,
    [original_timestamp]      DATETIME2 (7)  NULL,
    [sent_at]                 DATETIME2 (7)  NULL,
    [event_text]              NVARCHAR (512) NULL,
    [timestamp]               DATETIME2 (7)  NULL,
    [context_page_referrer]   NVARCHAR (512) NULL,
    [submit_requestId]        BIGINT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_RedShift_scotia_pursuits_submit_requestId] PRIMARY KEY CLUSTERED ([submit_requestId] ASC)
);

