CREATE TABLE [RedShift_hsbc_vi].[booking_event] (
    [id]                                                   NVARCHAR (512) NULL,
    [received_at]                                          DATETIME2 (7)  NULL,
    [uuid]                                                 BIGINT         NULL,
    [context_locale]                                       NVARCHAR (512) NULL,
    [context_page_url]                                     NVARCHAR (512) NULL,
    [sent_at]                                              DATETIME2 (7)  NULL,
    [booking_data_data_flight_sub_bookings]                NVARCHAR (512) NULL,
    [timestamp]                                            DATETIME2 (7)  NULL,
    [booking_data_data_billing_address_data_postcode]      NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_country]       NVARCHAR (512) NULL,
    [booking_data_data_confirmed_terms]                    BIT            NULL,
    [context_page_referrer]                                NVARCHAR (512) NULL,
    [original_timestamp]                                   DATETIME2 (7)  NULL,
    [anonymous_id]                                         NVARCHAR (512) NULL,
    [context_library_version]                              NVARCHAR (512) NULL,
    [context_user_agent]                                   NVARCHAR (512) NULL,
    [event]                                                NVARCHAR (512) NULL,
    [event_text]                                           NVARCHAR (512) NULL,
    [booking_data_data_browser_info_screen_width]          BIGINT         NULL,
    [context_ip]                                           NVARCHAR (512) NULL,
    [context_library_name]                                 NVARCHAR (512) NULL,
    [context_page_path]                                    NVARCHAR (512) NULL,
    [booking_data_data_browser_info_color_depth]           BIGINT         NULL,
    [booking_data_data_billing_address_data_city]          NVARCHAR (512) NULL,
    [booking_data_data_browser_info_screen_height]         BIGINT         NULL,
    [booking_data_data_hotel_sub_bookings]                 NVARCHAR (512) NULL,
    [context_page_title]                                   NVARCHAR (512) NULL,
    [securely_store_card_checkbox]                         NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_address_line1] NVARCHAR (512) NULL,
    [booking_data_data_browser_info_timezone_offset]       BIGINT         NULL,
    [booking_data_data_car_hire_sub_bookings]              NVARCHAR (512) NULL,
    [type]                                                 NVARCHAR (512) NULL,
    [booking_data_data_browser_info_java_enabled]          BIT            NULL,
    [user_id]                                              NVARCHAR (512) NULL,
    [uuid_ts]                                              DATETIME2 (7)  NULL,
    [booking_data_data_browser_info_language]              NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_house_number]  NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_id]            BIGINT         NULL,
    [booking_data_data_billing_address_data_latitude]      NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_longitude]     NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_url]           NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_preferred]     BIT            NULL,
    [booking_data_data_billing_address_data_type]          NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_address_line2] NVARCHAR (512) NULL,
    [booking_data_data_billing_address_data_state]         NVARCHAR (512) NULL
);

