CREATE TABLE [TenMAID_US].[Employees] (
    [Active]              BIT            NULL,
    [AllocatorID]         INT            NULL,
    [BuddyID]             INT            NULL,
    [CallMediaID]         INT            NULL,
    [ContractedHours]     FLOAT (53)     NULL,
    [CorporateGroupID]    INT            NULL,
    [CorporateSchemeID]   INT            NULL,
    [CreatedBy]           NVARCHAR (255) NULL,
    [DateCreated]         DATETIME       NULL,
    [DateJoined]          DATETIME       NULL,
    [DateLeaved]          DATETIME       NULL,
    [DateUpdated]         DATETIME       NULL,
    [EmployeeID]          INT            NOT NULL,
    [EmployeeType]        INT            NULL,
    [Extension]           NVARCHAR (50)  NULL,
    [Firstname]           NVARCHAR (255) NULL,
    [FTE]                 FLOAT (53)     NULL,
    [IsPasswordReset]     BIT            NULL,
    [JobAllocator]        BIT            NULL,
    [JobTitleID]          INT            NULL,
    [LastNameChangeDate]  DATETIME       NULL,
    [Locked]              BIT            NULL,
    [ManagerID]           INT            NULL,
    [Middlename]          NVARCHAR (50)  NULL,
    [Name]                NVARCHAR (50)  NULL,
    [NewRegionID]         INT            NULL,
    [NewSpecialistTeamID] INT            NULL,
    [NewSubRegionID]      INT            NULL,
    [NewSubTeamID]        INT            NULL,
    [NewTeamID]           INT            NULL,
    [NoOfTry]             SMALLINT       NULL,
    [OfficeID]            INT            NULL,
    [Password]            NVARCHAR (255) NULL,
    [PayrollOfficeID]     INT            NULL,
    [PwdChangedDate]      DATETIME       NULL,
    [RatingID]            INT            NULL,
    [ReceiveEmail]        BIT            NULL,
    [RegionID]            INT            NULL,
    [RemoteAccess]        INT            NULL,
    [SessionID]           VARCHAR (64)   NULL,
    [Sex]                 NCHAR (1)      NULL,
    [SpecialistTeamID]    INT            NULL,
    [SubTeamID]           SMALLINT       NULL,
    [Surname]             NVARCHAR (50)  NULL,
    [Team]                NVARCHAR (50)  NULL,
    [TeamID]              SMALLINT       NULL,
    [UpdatedBy]           INT            NULL,
    [Username]            NVARCHAR (255) NULL,
    CONSTRAINT [PK_TenMAID_US_Employees] PRIMARY KEY CLUSTERED ([EmployeeID] ASC)
);

