CREATE TABLE [TenMAID_US].[JobSatisfaction_Staging] (
    [CedarORBouquetID]          INT             NULL,
    [Cost]                      MONEY           NULL,
    [CostCurrencyID]            INT             NULL,
    [DateFeedbackReceived]      DATETIME        NULL,
    [DateResolved]              DATETIME        NULL,
    [ExternalSupplier]          NVARCHAR (150)  NULL,
    [FeedbackClassificationID]  INT             NULL,
    [FeedBackMilestoneID]       INT             NULL,
    [FeedbackTypeID]            INT             NULL,
    [FlaggedByEmployeeID]       INT             NULL,
    [FlaggedByID]               INT             NULL,
    [InternalFollowUp]          NVARCHAR (2000) NULL,
    [IsEmpInvolvedInResolution] INT             NULL,
    [IsLocked]                  BIT             NULL,
    [JobID]                     INT             NULL,
    [JobSatisfactionID]         INT             NOT NULL,
    [LimitedUpdatedByID]        INT             NULL,
    [LimitedUpdatedWhen]        DATETIME        NULL,
    [LMManagingJobID]           INT             NULL,
    [LockedBy]                  INT             NULL,
    [LockedWhen]                DATETIME        NULL,
    [LoggedByID]                INT             NULL,
    [MemberID]                  INT             NULL,
    [MemberSatisfactionID]      INT             NULL,
    [NatureOfFeedback]          NVARCHAR (2000) NULL,
    [NegativeClassificatonID]   INT             NULL,
    [OutcomeLiesWithEmployeeID] INT             NULL,
    [OutcomeLiesWithID]         INT             NULL,
    [OutcomeLiesWithSupplierID] INT             NULL,
    [OwnedByID]                 INT             NULL,
    [ResolutionEmp1]            INT             NULL,
    [ResolutionEmp2]            INT             NULL,
    [ResolutionInvolvedEmpID]   INT             NULL,
    [TrendID]                   INT             NULL,
    [UpdatedByID]               INT             NULL,
    [UpdatedWhen]               DATETIME        NULL,
    [WhatTenDid]                NVARCHAR (2000) NULL,
    [SYS_CHANGE_OPERATION]      NVARCHAR (1)    NULL,
    [SYS_CHANGE_VERSION]        BIGINT          NULL,
    CONSTRAINT [PK_TenMAID_US_JobSatisfaction_Staging] PRIMARY KEY CLUSTERED ([JobSatisfactionID] ASC)
);

