CREATE TABLE [TenMAID_US].[MemberJoiningDetails] (
    [AccountName]                   NVARCHAR (40) NULL,
    [BankName]                      NVARCHAR (40) NULL,
    [CreatedBy]                     INT           NULL,
    [DateCreated]                   DATETIME      NULL,
    [DateOfCancellation]            DATETIME      NULL,
    [DateOfNextRenewal]             DATETIME      NULL,
    [DateUpdated]                   DATETIME      NULL,
    [DirectDebit]                   BIT           NULL,
    [FirstLM]                       INT           NULL,
    [FirstPaymentAmount]            MONEY         NULL,
    [FirstPaymentTaken]             BIT           NULL,
    [ForeignMemberJoiningDetailsID] INT           NULL,
    [IsIDCheckCompleted]            BIT           NULL,
    [IsInstallmentCreditCard]       BIT           NULL,
    [IsMemberPackSent]              BIT           NULL,
    [IsMemberShipCancelled]         BIT           NULL,
    [IsOrderReceived]               BIT           NULL,
    [IsOrderSent]                   BIT           NULL,
    [IsReferred]                    BIT           NULL,
    [IsRefundRequired]              BIT           NULL,
    [IsRenewalAgreed]               BIT           NULL,
    [IsTCagreed]                    BIT           NULL,
    [IsWelcomeCall]                 BIT           NULL,
    [IsWelcomeEmail]                BIT           NULL,
    [JoiningDate]                   DATETIME      NULL,
    [MemberID]                      INT           NOT NULL,
    [MemberJobAllowance]            INT           NULL,
    [MemberJoiningDetailsID]        INT           NOT NULL,
    [MembershipFees]                MONEY         NULL,
    [MembershipLength]              INT           NULL,
    [MemberUsagePeriod]             INT           NULL,
    [PaidDate]                      DATETIME      NULL,
    [ReceivedStandingOrderFormDate] DATETIME      NULL,
    [RenewalDate]                   DATETIME      NULL,
    [RenewalDue]                    DATETIME      NULL,
    [RenewalToCommence]             DATETIME      NULL,
    [SentToBank]                    BIT           NULL,
    [SingedUpBy]                    INT           NULL,
    [UpdatedBy]                     INT           NULL,
    [WhenFirstPaymentReceived]      DATETIME      NULL,
    CONSTRAINT [PK_TenMAID_US_MemberJoiningDetails] PRIMARY KEY CLUSTERED ([MemberJoiningDetailsID] ASC)
);

