CREATE TABLE [TenMAID_US].[Members] (
    [AccountingCode]            NVARCHAR (30)  NULL,
    [AdditionalMemberID]        INT            NULL,
    [AlertGreen]                NVARCHAR (255) NULL,
    [AmadeusInstance]           INT            NULL,
    [AmadeusProfileID]          NVARCHAR (50)  NULL,
    [AssignEmployeeID]          INT            NULL,
    [AttriumID]                 INT            NULL,
    [CitiCorporateID]           INT            NULL,
    [CitiCustomerID]            NVARCHAR (150) NULL,
    [ClientRefNo]               NVARCHAR (50)  NULL,
    [CompanyName]               NVARCHAR (100) NULL,
    [ConsentID]                 INT            NULL,
    [CountryID]                 NCHAR (2)      NULL,
    [CreatedBy]                 INT            NULL,
    [DateCreated]               DATETIME       NULL,
    [DateJoined]                DATETIME       NULL,
    [DateOfExpiry]              DATETIME       NULL,
    [DateReceivedQuestionnaire] DATETIME       NULL,
    [DateUpdated]               DATETIME       NULL,
    [DigitalId]                 INT            NULL,
    [DOB]                       DATETIME       NULL,
    [DolphinID]                 VARCHAR (50)   NULL,
    [FirstName]                 NVARCHAR (50)  NULL,
    [ForeignMemberID]           INT            NULL,
    [IsImportant]               BIT            NULL,
    [IsInvestor]                BIT            NULL,
    [IsMain]                    BIT            NULL,
    [IsNewsSend]                SMALLINT       NULL,
    [IsNewsSend1]               BIT            NULL,
    [IsWithWexas]               BIT            NULL,
    [JobCount]                  INT            NULL,
    [JobTitle]                  NVARCHAR (100) NULL,
    [LanguageID]                NVARCHAR (100) NULL,
    [LastDateMet]               DATETIME       NULL,
    [LocationID]                INT            NULL,
    [MemberGroupID]             INT            NULL,
    [MemberID]                  INT            NOT NULL,
    [MembershipStatusID]        INT            NULL,
    [MemberSurveyDate]          DATETIME       NULL,
    [MemberSurveyID]            INT            NULL,
    [MiddleName]                NVARCHAR (50)  NULL,
    [OldMemberID]               INT            NULL,
    [PreferredLifestyleLM]      INT            NULL,
    [PreferredTravelLM]         INT            NULL,
    [PrimaryEmail]              NVARCHAR (255) NULL,
    [PrimaryEmployeeID]         INT            NULL,
    [PrimaryID]                 INT            NULL,
    [PrimaryLMID]               INT            NULL,
    [PrimaryMobile]             NVARCHAR (200) NULL,
    [RBSAPrimaryID]             INT            NULL,
    [Reference1]                NVARCHAR (255) NULL,
    [Reference2]                NVARCHAR (255) NULL,
    [Reference3]                NVARCHAR (255) NULL,
    [RelationshipsToPM]         NVARCHAR (50)  NULL,
    [salesForceID]              VARCHAR (60)   NULL,
    [SatisfactionID]            INT            NULL,
    [SchemeID]                  INT            NULL,
    [Sex]                       CHAR (1)       NULL,
    [Surname]                   NVARCHAR (50)  NULL,
    [TeamLeader]                INT            NULL,
    [TempEmployeeID]            INT            NULL,
    [TimeZoneID]                INT            NULL,
    [TitleID]                   INT            NULL,
    [TTSCustomerID]             INT            NULL,
    [UpdatedBy]                 INT            NULL,
    [updatesusage]              DATETIME       NULL,
    [UsageAlert]                INT            NULL,
    [VRegID]                    INT            NULL,
    CONSTRAINT [PK_TenMAID_US_Members] PRIMARY KEY CLUSTERED ([MemberID] ASC)
);

