CREATE TABLE [TenMAID_US].[SupInvoices_Staging] (
    [ActualCommission]                    MONEY          NULL,
    [AmendmentFees]                       MONEY          NULL,
    [CancellationFees]                    MONEY          NULL,
    [CommisionInOtherCurrency]            MONEY          NULL,
    [CommissionableAmountInGBP]           MONEY          NULL,
    [CommissionableAmountInOtherCurrency] MONEY          NULL,
    [CommissionByLm]                      FLOAT (53)     NULL,
    [CommissionByLmInGBP]                 MONEY          NULL,
    [CreditCardFees]                      MONEY          NULL,
    [CurrencyID]                          INT            NULL,
    [CurrencyValue]                       FLOAT (53)     NULL,
    [DateAdded]                           DATETIME       NULL,
    [DateCheckedOut]                      DATETIME       NULL,
    [DateCreated]                         DATETIME       NULL,
    [DatePostedInSun]                     DATETIME       NULL,
    [department]                          INT            NULL,
    [F_City]                              NVARCHAR (50)  NULL,
    [F_CountryName]                       NVARCHAR (50)  NULL,
    [F_Email]                             NVARCHAR (200) NULL,
    [F_HouseName]                         NVARCHAR (50)  NULL,
    [F_HouseNumber]                       NVARCHAR (50)  NULL,
    [F_Name]                              NVARCHAR (150) NULL,
    [F_PostCode]                          NVARCHAR (50)  NULL,
    [F_State]                             NVARCHAR (50)  NULL,
    [F_Street1]                           NVARCHAR (50)  NULL,
    [F_Street2]                           NVARCHAR (50)  NULL,
    [FixedCommission]                     BIT            NULL,
    [FlightAirTax]                        MONEY          NULL,
    [IataNumber]                          VARCHAR (30)   NULL,
    [IncludeExtraText]                    BIT            NULL,
    [InvoiceAmt]                          FLOAT (53)     NULL,
    [InvoiceNumber]                       NVARCHAR (250) NULL,
    [InvoiceOffice]                       INT            NULL,
    [InvoicePath]                         NVARCHAR (100) NULL,
    [InvoiceReference]                    VARCHAR (44)   NULL,
    [InvoiceSentDate]                     DATETIME       NULL,
    [IsActualPaymentReceived]             BIT            NULL,
    [IsATOLPBooking]                      BIT            NULL,
    [IsCommissionable]                    BIT            NULL,
    [IsFirstPage]                         BIT            NULL,
    [IsGDSBooking]                        BIT            NULL,
    [IsInvoiceSent]                       BIT            NULL,
    [IsSageDataUpdated]                   BIT            NULL,
    [IsSecondPage]                        BIT            NULL,
    [IsSupplierUKBased]                   BIT            NULL,
    [IsTravelJob]                         BIT            NULL,
    [IsUploadedToSun]                     BIT            NULL,
    [IsVatIncluded]                       BIT            NULL,
    [IsVATIncludedONJobCost]              BIT            NULL,
    [IsVatKnown]                          BIT            NULL,
    [JobAutoCloseDate]                    DATETIME       NULL,
    [JobDate]                             DATETIME       NULL,
    [JobID]                               INT            NULL,
    [JobName]                             NVARCHAR (150) NULL,
    [MemberCountryID]                     INT            NULL,
    [MemberInvoiceAddress]                NVARCHAR (700) NULL,
    [MemberInvoiceDate]                   DATETIME       NULL,
    [MemberName]                          NVARCHAR (100) NULL,
    [NoOfAdults]                          SMALLINT       NULL,
    [NoOfChildren]                        SMALLINT       NULL,
    [NoOfInfants]                         SMALLINT       NULL,
    [NoOfNights]                          SMALLINT       NULL,
    [NoOfRooms]                           SMALLINT       NULL,
    [PaymentProcID]                       SMALLINT       NULL,
    [PaymentReceived]                     BIT            NULL,
    [PaymentTerm]                         SMALLINT       NULL,
    [PvtUkVatTypeID]                      INT            NULL,
    [S_PostCode]                          NVARCHAR (50)  NULL,
    [SupInvoiceID]                        INT            NOT NULL,
    [SupplierID]                          INT            NULL,
    [SupplierRevenueInGBP]                MONEY          NULL,
    [TicketingFees]                       MONEY          NULL,
    [TotalInvoiceInGBP]                   MONEY          NULL,
    [TotalInvoiceInOtherCurrency]         MONEY          NULL,
    [TotalPaidInGBP]                      MONEY          NULL,
    [TotalPaidInOtherCurrency]            MONEY          NULL,
    [VatLiabilityInGBP]                   MONEY          NULL,
    [VendorCommissionPercent]             FLOAT (53)     NULL,
    [VendorID]                            INT            NULL,
    [VendorJobCommission]                 FLOAT (53)     NULL,
    [Version]                             INT            NULL,
    [WhenPaymentTaken]                    DATETIME       NULL,
    [SYS_CHANGE_OPERATION]                NVARCHAR (1)   NULL,
    [SYS_CHANGE_VERSION]                  BIGINT         NULL,
    CONSTRAINT [PK_TenMAID_US_SupInvoices_Staging] PRIMARY KEY CLUSTERED ([SupInvoiceID] ASC)
);

