CREATE TABLE [Cloak].[TaskHistory] (
    [ChainEndTime]               DATETIME      NOT NULL,
    [CHID]                       INT           NOT NULL,
    [CompletionCodeID]           INT           NOT NULL,
    [Conferenced]                INT           NULL,
    [ConfSource]                 INT           NOT NULL,
    [ConnectingDuration]         INT           NULL,
    [ConnectionAttempts]         TINYINT       NOT NULL,
    [ConnectorInfo]              VARCHAR (255) NULL,
    [ConsultationAllocated]      DATETIME      NULL,
    [ConsultationArrived]        DATETIME      NULL,
    [ConsultationConnected]      DATETIME      NULL,
    [ConsultationEndedTime]      DATETIME      NULL,
    [ConsultationTask]           INT           NOT NULL,
    [ContactDuration]            INT           NULL,
    [CustomData]                 VARCHAR (64)  NULL,
    [CustomerID]                 INT           NULL,
    [CustomValue]                INT           NULL,
    [Date]                       DATETIME      NOT NULL,
    [DateID]                     INT           NULL,
    [DestID]                     INT           NOT NULL,
    [DID]                        INT           NOT NULL,
    [DisconnectedBy]             INT           NOT NULL,
    [DriverOutcome]              INT           NOT NULL,
    [DTID]                       INT           NOT NULL,
    [EID]                        INT           NULL,
    [ExternalTarget]             VARCHAR (255) NULL,
    [FromID]                     VARCHAR (255) NULL,
    [GroupID]                    INT           NOT NULL,
    [InterruptTimeSecs]          INT           NOT NULL,
    [Outcome]                    INT           NULL,
    [OutcomeCode]                INT           NOT NULL,
    [OverallDuration]            INT           NULL,
    [ParentTaskID]               INT           NOT NULL,
    [PartialTaskConsultationID]  INT           NULL,
    [PreferredArrivedTime]       DATETIME      NULL,
    [PreferredTeam]              INT           NOT NULL,
    [PreferredUser]              INT           NOT NULL,
    [Q41TID]                     INT           NOT NULL,
    [QID]                        INT           NOT NULL,
    [QueueSource]                INT           NOT NULL,
    [QueueTarget]                INT           NULL,
    [QueuingDuration]            INT           NULL,
    [QueuingInWkingTimeDuration] INT           NOT NULL,
    [ReasonCode]                 INT           NOT NULL,
    [RecordType]                 INT           NOT NULL,
    [ReportClass]                INT           NULL,
    [RequiresConnection]         INT           NOT NULL,
    [RoutedFlag]                 INT           NOT NULL,
    [RouterArrived]              DATETIME      NULL,
    [RouterDuration]             INT           NULL,
    [RouterID]                   INT           NULL,
    [RouterRouted]               DATETIME      NULL,
    [RouterTagData]              VARCHAR (255) NULL,
    [RQID]                       INT           NOT NULL,
    [SiteID]                     INT           NULL,
    [TaskAllocatedTime]          DATETIME      NULL,
    [TaskArrivedTime]            DATETIME      NULL,
    [TaskConnectedTime]          DATETIME      NULL,
    [TaskEndedTime]              DATETIME      NULL,
    [TaskInterruptions]          INT           NOT NULL,
    [TaskPriority]               INT           NOT NULL,
    [TaskSource]                 INT           NULL,
    [TaskTransferred]            INT           NOT NULL,
    [TaskWrapUpTime]             DATETIME      NULL,
    [TimeID]                     INT           NULL,
    [TimeOfAction]               DATETIME      NOT NULL,
    [ToID]                       VARCHAR (255) NULL,
    [TransferInFlag]             INT           NOT NULL,
    [TransferInOutcome]          INT           NOT NULL,
    [TransferInType]             INT           NOT NULL,
    [TransferNum]                INT           NOT NULL,
    [TransferOutFlag]            INT           NOT NULL,
    [TransferOutOutcome]         INT           NOT NULL,
    [TransferOutType]            INT           NOT NULL,
    [Type]                       INT           NOT NULL,
    [UID]                        INT           NOT NULL,
    [UserSource]                 INT           NOT NULL,
    [UserTarget]                 INT           NULL,
    [UTID]                       INT           NOT NULL,
    [WasUserToUserConsult]       INT           NOT NULL,
    [WasUserToXTAConsult]        INT           NOT NULL,
    [WrapDuration]               INT           NULL,
    [WrapInterruptTimeSecs]      INT           NULL,
    CONSTRAINT [PK_Cloak_TaskHistory_Q41TID] PRIMARY KEY CLUSTERED ([Q41TID] ASC)
);

