CREATE TABLE [Cloak].[Users] (
    [AdvanceUserType]     INT           NOT NULL,
    [Alertable]           INT           NOT NULL,
    [AssistanceEnabled]   INT           NOT NULL,
    [AutoAnswer]          TINYINT       NOT NULL,
    [AvailableTime]       INT           NOT NULL,
    [CreateDate]          DATETIME      NOT NULL,
    [DeleteDate]          DATETIME      NULL,
    [DevWaitingTime]      INT           NOT NULL,
    [DiallingTime]        INT           NOT NULL,
    [Disabled]            BIT           NOT NULL,
    [Email]               VARCHAR (255) NULL,
    [ExtendWUTO]          TINYINT       NOT NULL,
    [Extension]           VARCHAR (10)  NULL,
    [FirstName]           VARCHAR (255) NULL,
    [GroupID]             INT           NOT NULL,
    [IgnoreWrapupTimeout] TINYINT       NOT NULL,
    [KnownToAdvance]      INT           NULL,
    [LastLoggedOn]        DATETIME      NULL,
    [LastStatsReset]      DATETIME      NULL,
    [LoggedOnTime]        INT           NOT NULL,
    [LogonID]             VARCHAR (20)  NULL,
    [ModifiedBy]          INT           NULL,
    [NotAvailableTime]    INT           NOT NULL,
    [Password]            VARCHAR (64)  NOT NULL,
    [PreviewTime]         INT           NOT NULL,
    [ProductiveTime]      INT           NOT NULL,
    [SiteID]              INT           NULL,
    [SMS]                 VARCHAR (31)  NULL,
    [Surname]             VARCHAR (255) NULL,
    [TeamID]              INT           NOT NULL,
    [TotalTasks]          INT           NOT NULL,
    [UnansweredTasks]     INT           NOT NULL,
    [UserID]              INT           NOT NULL,
    [UserState]           INT           NOT NULL,
    [UserType]            INT           NOT NULL,
    [ViewID]              INT           NOT NULL,
    [WaitingTime]         INT           NOT NULL,
    [WrapUpTime]          INT           NOT NULL,
    CONSTRAINT [PK_Cloak_Users] PRIMARY KEY CLUSTERED ([UserID] ASC)
);

